/*
 * Kartverkets åpne API for søk etter stedsnavn
 *
 *  API for søk etter stedsnavn. Man kan for eksempel søke etter et navn, et sted (et sted kan ha flere navn) eller steder i nærheten av et punkt. APIet returnerer kun de første 5000 resultatene.  Det er ikke nødvendig med innlogging/autorisasjon for å bruke APIet.  Medio desember 2023 ble APIet flyttet til et nytt endepunkt som er tilgjengelig på <a href=\"https://api.kartverket.no/stedsnavn/v1\">https://api.kartverket.no/stedsnavn/v1</a>. Det tidligere endepunktet <a href=\"https://ws.geonorge.no/stedsnavn/v1\">https://ws.geonorge.no/stedsnavn/v1</a> vil være tilgjengelig inntil videre, og vil fungere som en proxy til det nye endepunktet. Vi anbefaler likevel å bytte til det nye endepunktet.  Større eller ikke-kompatible endringer i APIet vil bli annonsert med minst 3 måneder forvarsel på <a href=\"https://status.kartverket.no\">https://status.kartverket.no</a>.     
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Metadata {
    /// Sidenummeret som skal returneres. Minimum 1, maksimum 500.
    #[serde(rename = "side", skip_serializing_if = "Option::is_none")]
    pub side: Option<i32>,
    /// Søkestrengen som ble sendt inn til API-et.
    #[serde(rename = "sokeStreng", skip_serializing_if = "Option::is_none")]
    pub soke_streng: Option<String>,
    /// Antall treff som søket returnerte. Hvis det er et tungt søk er antallet ofte et grovestimat, ikke et nøyaktig antall.
    #[serde(rename = "totaltAntallTreff", skip_serializing_if = "Option::is_none")]
    pub totalt_antall_treff: Option<i32>,
    /// Antall treff per side. Minimum 1, maksimum 500.
    #[serde(rename = "treffPerSide", skip_serializing_if = "Option::is_none")]
    pub treff_per_side: Option<i32>,
    /// Angi det koordinatsystemet som du ønsker at geometrien i returen skal transformeres til, oppgis som en SRID (altså tallene i en EPSG-kode, f.eks. 4258 eller 25833). Standard er 4258.
    #[serde(rename = "utkoordsys", skip_serializing_if = "Option::is_none")]
    pub utkoordsys: Option<i32>,
    /// Viser treff fra og medobjekt nummer X i responsen.
    #[serde(rename = "viserFra", skip_serializing_if = "Option::is_none")]
    pub viser_fra: Option<i32>,
    /// Viser treff til og med objekt nummer X i responsen.
    #[serde(rename = "viserTil", skip_serializing_if = "Option::is_none")]
    pub viser_til: Option<i32>,
}

impl Metadata {
    pub fn new() -> Metadata {
        Metadata {
            side: None,
            soke_streng: None,
            totalt_antall_treff: None,
            treff_per_side: None,
            utkoordsys: None,
            viser_fra: None,
            viser_til: None,
        }
    }
}

