/*
 * Kartverkets åpne API for søk etter stedsnavn
 *
 *  API for søk etter stedsnavn. Man kan for eksempel søke etter et navn, et sted (et sted kan ha flere navn) eller steder i nærheten av et punkt. APIet returnerer kun de første 5000 resultatene.  Det er ikke nødvendig med innlogging/autorisasjon for å bruke APIet.  Medio desember 2023 ble APIet flyttet til et nytt endepunkt som er tilgjengelig på <a href=\"https://api.kartverket.no/stedsnavn/v1\">https://api.kartverket.no/stedsnavn/v1</a>. Det tidligere endepunktet <a href=\"https://ws.geonorge.no/stedsnavn/v1\">https://ws.geonorge.no/stedsnavn/v1</a> vil være tilgjengelig inntil videre, og vil fungere som en proxy til det nye endepunktet. Vi anbefaler likevel å bytte til det nye endepunktet.  Større eller ikke-kompatible endringer i APIet vil bli annonsert med minst 3 måneder forvarsel på <a href=\"https://status.kartverket.no\">https://status.kartverket.no</a>.     
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Navneobjekttype {
    /// Objekttypen som et sted kan tilhøre, f.eks en by, elv eller kirke
    #[serde(rename = "navneobjekttype", skip_serializing_if = "Option::is_none")]
    pub navneobjekttype: Option<String>,
    /// 
    #[serde(rename = "navneobjekttypekode", skip_serializing_if = "Option::is_none")]
    pub navneobjekttypekode: Option<String>,
}

impl Navneobjekttype {
    pub fn new() -> Navneobjekttype {
        Navneobjekttype {
            navneobjekttype: None,
            navneobjekttypekode: None,
        }
    }
}

