/*
 * Kartverkets åpne API for søk etter stedsnavn
 *
 *  API for søk etter stedsnavn. Man kan for eksempel søke etter et navn, et sted (et sted kan ha flere navn) eller steder i nærheten av et punkt. APIet returnerer kun de første 5000 resultatene.  Det er ikke nødvendig med innlogging/autorisasjon for å bruke APIet.  Medio desember 2023 ble APIet flyttet til et nytt endepunkt som er tilgjengelig på <a href=\"https://api.kartverket.no/stedsnavn/v1\">https://api.kartverket.no/stedsnavn/v1</a>. Det tidligere endepunktet <a href=\"https://ws.geonorge.no/stedsnavn/v1\">https://ws.geonorge.no/stedsnavn/v1</a> vil være tilgjengelig inntil videre, og vil fungere som en proxy til det nye endepunktet. Vi anbefaler likevel å bytte til det nye endepunktet.  Større eller ikke-kompatible endringer i APIet vil bli annonsert med minst 3 måneder forvarsel på <a href=\"https://status.kartverket.no\">https://status.kartverket.no</a>.     
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Punkt {
    /// Distanse i meter til punktet det ble søkt etter.
    #[serde(rename = "meterFraPunkt", skip_serializing_if = "Option::is_none")]
    pub meter_fra_punkt: Option<i32>,
    /// Objekttypen som et sted kan tilhøre, f.eks en by, elv eller kirke
    #[serde(rename = "navneobjekttype", skip_serializing_if = "Option::is_none")]
    pub navneobjekttype: Option<String>,
    /// Et konstruert representasjonspunkt for stedsnavnet.
    #[serde(rename = "representasjonspunkt", skip_serializing_if = "Option::is_none")]
    pub representasjonspunkt: Option<Box<models::Representasjonspunkt>>,
    #[serde(rename = "stedsnavn", skip_serializing_if = "Option::is_none")]
    pub stedsnavn: Option<Vec<models::SkrivemateJson>>,
    /// Identifikator for et sted.
    #[serde(rename = "stedsnummer", skip_serializing_if = "Option::is_none")]
    pub stedsnummer: Option<i32>,
    /// Status for selve stedet. Et sted kan være et relikt (historisk), aktivt eller planlagt sted. En kommune som ikke lenger eksisterer er f.eks. relikt, mens en bru som skal bygges er planlagt.
    #[serde(rename = "stedstatus", skip_serializing_if = "Option::is_none")]
    pub stedstatus: Option<String>,
}

impl Punkt {
    pub fn new() -> Punkt {
        Punkt {
            meter_fra_punkt: None,
            navneobjekttype: None,
            representasjonspunkt: None,
            stedsnavn: None,
            stedsnummer: None,
            stedstatus: None,
        }
    }
}

