/*
 * Kartverkets åpne API for søk etter stedsnavn
 *
 *  API for søk etter stedsnavn. Man kan for eksempel søke etter et navn, et sted (et sted kan ha flere navn) eller steder i nærheten av et punkt. APIet returnerer kun de første 5000 resultatene.  Det er ikke nødvendig med innlogging/autorisasjon for å bruke APIet.  Medio desember 2023 ble APIet flyttet til et nytt endepunkt som er tilgjengelig på <a href=\"https://api.kartverket.no/stedsnavn/v1\">https://api.kartverket.no/stedsnavn/v1</a>. Det tidligere endepunktet <a href=\"https://ws.geonorge.no/stedsnavn/v1\">https://ws.geonorge.no/stedsnavn/v1</a> vil være tilgjengelig inntil videre, og vil fungere som en proxy til det nye endepunktet. Vi anbefaler likevel å bytte til det nye endepunktet.  Større eller ikke-kompatible endringer i APIet vil bli annonsert med minst 3 måneder forvarsel på <a href=\"https://status.kartverket.no\">https://status.kartverket.no</a>.     
 *
 * The version of the OpenAPI document: 1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Skrivemate {
    #[serde(rename = "fylker", skip_serializing_if = "Option::is_none")]
    pub fylker: Option<Vec<models::Fylker>>,
    #[serde(rename = "kommuner", skip_serializing_if = "Option::is_none")]
    pub kommuner: Option<Vec<models::Kommuner>>,
    /// Objekttypen som et sted kan tilhøre, f.eks en by, elv eller kirke
    #[serde(rename = "navneobjekttype", skip_serializing_if = "Option::is_none")]
    pub navneobjekttype: Option<String>,
    /// Angir statusen til navnet, f.eks. om det er et hovednavn eller sidenavn.
    #[serde(rename = "navnestatus", skip_serializing_if = "Option::is_none")]
    pub navnestatus: Option<String>,
    /// Et konstruert representasjonspunkt for stedsnavnet.
    #[serde(rename = "representasjonspunkt", skip_serializing_if = "Option::is_none")]
    pub representasjonspunkt: Option<Box<models::Representasjonspunkt>>,
    /// En spesifikk måte å skrive et stedsnavn på.
    #[serde(rename = "skrivemåte", skip_serializing_if = "Option::is_none")]
    pub skrivemte: Option<String>,
    /// Hvilken status denne skrivemåten har, f.eks. om den er historisk eller godkjent.
    #[serde(rename = "skrivemåtestatus", skip_serializing_if = "Option::is_none")]
    pub skrivemtestatus: Option<String>,
    /// Språket til skrivemåten/navnet.
    #[serde(rename = "språk", skip_serializing_if = "Option::is_none")]
    pub sprk: Option<String>,
    /// Identifikator for et sted.
    #[serde(rename = "stedsnummer", skip_serializing_if = "Option::is_none")]
    pub stedsnummer: Option<i32>,
    /// Status for selve stedet. Et sted kan være et relikt (historisk), aktivt eller planlagt sted. En kommune som ikke lenger eksisterer er f.eks. relikt, mens en bru som skal bygges er planlagt.
    #[serde(rename = "stedstatus", skip_serializing_if = "Option::is_none")]
    pub stedstatus: Option<String>,
}

impl Skrivemate {
    pub fn new() -> Skrivemate {
        Skrivemate {
            fylker: None,
            kommuner: None,
            navneobjekttype: None,
            navnestatus: None,
            representasjonspunkt: None,
            skrivemte: None,
            skrivemtestatus: None,
            sprk: None,
            stedsnummer: None,
            stedstatus: None,
        }
    }
}

