/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForecastTimePeriod : Weather parameters valid for a specified time period.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastTimePeriod {
    /// Maximum air temperature in period
    #[serde(rename = "air_temperature_max", skip_serializing_if = "Option::is_none")]
    pub air_temperature_max: Option<f64>,
    /// Minimum air temperature in period
    #[serde(rename = "air_temperature_min", skip_serializing_if = "Option::is_none")]
    pub air_temperature_min: Option<f64>,
    /// Best estimate for amount of precipitation for this period
    #[serde(rename = "precipitation_amount", skip_serializing_if = "Option::is_none")]
    pub precipitation_amount: Option<f64>,
    /// Maximum amount of precipitation for this period
    #[serde(rename = "precipitation_amount_max", skip_serializing_if = "Option::is_none")]
    pub precipitation_amount_max: Option<f64>,
    /// Minimum amount of precipitation for this period
    #[serde(rename = "precipitation_amount_min", skip_serializing_if = "Option::is_none")]
    pub precipitation_amount_min: Option<f64>,
    /// Probability of any precipitation coming for this period
    #[serde(rename = "probability_of_precipitation", skip_serializing_if = "Option::is_none")]
    pub probability_of_precipitation: Option<f64>,
    /// Probability of any thunder coming for this period
    #[serde(rename = "probability_of_thunder", skip_serializing_if = "Option::is_none")]
    pub probability_of_thunder: Option<f64>,
    /// Maximum ultraviolet index if sky is clear
    #[serde(rename = "ultraviolet_index_clear_sky_max", skip_serializing_if = "Option::is_none")]
    pub ultraviolet_index_clear_sky_max: Option<f64>,
}

impl ForecastTimePeriod {
    /// Weather parameters valid for a specified time period.
    pub fn new() -> ForecastTimePeriod {
        ForecastTimePeriod {
            air_temperature_max: None,
            air_temperature_min: None,
            precipitation_amount: None,
            precipitation_amount_max: None,
            precipitation_amount_min: None,
            probability_of_precipitation: None,
            probability_of_thunder: None,
            ultraviolet_index_clear_sky_max: None,
        }
    }
}

