/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastMeta {
    #[serde(rename = "units")]
    pub units: Box<models::ForecastUnits>,
    /// Update time for this forecast
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ForecastMeta {
    pub fn new(units: models::ForecastUnits, updated_at: String) -> ForecastMeta {
        ForecastMeta {
            units: Box::new(units),
            updated_at,
        }
    }
}

