/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForecastTimeStepData : Forecast for a specific time
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastTimeStepData {
    #[serde(rename = "instant")]
    pub instant: Box<models::ForecastTimeStepDataInstant>,
    #[serde(rename = "next_12_hours", skip_serializing_if = "Option::is_none")]
    pub next_12_hours: Option<Box<models::ForecastTimeStepDataNext12Hours>>,
    #[serde(rename = "next_1_hours", skip_serializing_if = "Option::is_none")]
    pub next_1_hours: Option<Box<models::ForecastTimeStepDataNext1Hours>>,
    #[serde(rename = "next_6_hours", skip_serializing_if = "Option::is_none")]
    pub next_6_hours: Option<Box<models::ForecastTimeStepDataNext6Hours>>,
}

impl ForecastTimeStepData {
    /// Forecast for a specific time
    pub fn new(instant: models::ForecastTimeStepDataInstant) -> ForecastTimeStepData {
        ForecastTimeStepData {
            instant: Box::new(instant),
            next_12_hours: None,
            next_1_hours: None,
            next_6_hours: None,
        }
    }
}

