/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastTimeStep {
    #[serde(rename = "data")]
    pub data: Box<models::ForecastTimeStepData>,
    /// The time these forecast values are valid for. Timestamp in format YYYY-MM-DDThh:mm:ssZ (ISO 8601)
    #[serde(rename = "time")]
    pub time: String,
}

impl ForecastTimeStep {
    pub fn new(data: models::ForecastTimeStepData, time: String) -> ForecastTimeStep {
        ForecastTimeStep {
            data: Box::new(data),
            time,
        }
    }
}

