/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForecastTimeInstant : Weather parameters valid for a specific point in time.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastTimeInstant {
    /// Air pressure at sea level
    #[serde(rename = "air_pressure_at_sea_level", skip_serializing_if = "Option::is_none")]
    pub air_pressure_at_sea_level: Option<f64>,
    /// Air temperature
    #[serde(rename = "air_temperature", skip_serializing_if = "Option::is_none")]
    pub air_temperature: Option<f64>,
    /// Amount of sky covered by clouds.
    #[serde(rename = "cloud_area_fraction", skip_serializing_if = "Option::is_none")]
    pub cloud_area_fraction: Option<f64>,
    /// Amount of sky covered by clouds at high elevation.
    #[serde(rename = "cloud_area_fraction_high", skip_serializing_if = "Option::is_none")]
    pub cloud_area_fraction_high: Option<f64>,
    /// Amount of sky covered by clouds at low elevation.
    #[serde(rename = "cloud_area_fraction_low", skip_serializing_if = "Option::is_none")]
    pub cloud_area_fraction_low: Option<f64>,
    /// Amount of sky covered by clouds at medium elevation.
    #[serde(rename = "cloud_area_fraction_medium", skip_serializing_if = "Option::is_none")]
    pub cloud_area_fraction_medium: Option<f64>,
    /// Dew point temperature at sea level
    #[serde(rename = "dew_point_temperature", skip_serializing_if = "Option::is_none")]
    pub dew_point_temperature: Option<f64>,
    /// Amount of area covered by fog.
    #[serde(rename = "fog_area_fraction", skip_serializing_if = "Option::is_none")]
    pub fog_area_fraction: Option<f64>,
    /// Amount of humidity in the air.
    #[serde(rename = "relative_humidity", skip_serializing_if = "Option::is_none")]
    pub relative_humidity: Option<f64>,
    /// The direction wind is coming from, in degrees clockwise from North
    #[serde(rename = "wind_from_direction", skip_serializing_if = "Option::is_none")]
    pub wind_from_direction: Option<f64>,
    /// Speed of wind
    #[serde(rename = "wind_speed", skip_serializing_if = "Option::is_none")]
    pub wind_speed: Option<f64>,
    /// Speed of wind gust
    #[serde(rename = "wind_speed_of_gust", skip_serializing_if = "Option::is_none")]
    pub wind_speed_of_gust: Option<f64>,
}

impl ForecastTimeInstant {
    /// Weather parameters valid for a specific point in time.
    pub fn new() -> ForecastTimeInstant {
        ForecastTimeInstant {
            air_pressure_at_sea_level: None,
            air_temperature: None,
            cloud_area_fraction: None,
            cloud_area_fraction_high: None,
            cloud_area_fraction_low: None,
            cloud_area_fraction_medium: None,
            dew_point_temperature: None,
            fog_area_fraction: None,
            relative_humidity: None,
            wind_from_direction: None,
            wind_speed: None,
            wind_speed_of_gust: None,
        }
    }
}

