/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForecastTimeStepDataInstant : Parameters which applies to this exact point in time
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastTimeStepDataInstant {
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Box<models::ForecastTimeInstant>>,
}

impl ForecastTimeStepDataInstant {
    /// Parameters which applies to this exact point in time
    pub fn new() -> ForecastTimeStepDataInstant {
        ForecastTimeStepDataInstant {
            details: None,
        }
    }
}

