/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastUnits {
    #[serde(rename = "air_pressure_at_sea_level", skip_serializing_if = "Option::is_none")]
    pub air_pressure_at_sea_level: Option<String>,
    #[serde(rename = "air_temperature", skip_serializing_if = "Option::is_none")]
    pub air_temperature: Option<String>,
    #[serde(rename = "air_temperature_max", skip_serializing_if = "Option::is_none")]
    pub air_temperature_max: Option<String>,
    #[serde(rename = "air_temperature_min", skip_serializing_if = "Option::is_none")]
    pub air_temperature_min: Option<String>,
    #[serde(rename = "cloud_area_fraction", skip_serializing_if = "Option::is_none")]
    pub cloud_area_fraction: Option<String>,
    #[serde(rename = "cloud_area_fraction_high", skip_serializing_if = "Option::is_none")]
    pub cloud_area_fraction_high: Option<String>,
    #[serde(rename = "cloud_area_fraction_low", skip_serializing_if = "Option::is_none")]
    pub cloud_area_fraction_low: Option<String>,
    #[serde(rename = "cloud_area_fraction_medium", skip_serializing_if = "Option::is_none")]
    pub cloud_area_fraction_medium: Option<String>,
    #[serde(rename = "dew_point_temperature", skip_serializing_if = "Option::is_none")]
    pub dew_point_temperature: Option<String>,
    #[serde(rename = "fog_area_fraction", skip_serializing_if = "Option::is_none")]
    pub fog_area_fraction: Option<String>,
    #[serde(rename = "precipitation_amount", skip_serializing_if = "Option::is_none")]
    pub precipitation_amount: Option<String>,
    #[serde(rename = "precipitation_amount_max", skip_serializing_if = "Option::is_none")]
    pub precipitation_amount_max: Option<String>,
    #[serde(rename = "precipitation_amount_min", skip_serializing_if = "Option::is_none")]
    pub precipitation_amount_min: Option<String>,
    #[serde(rename = "probability_of_precipitation", skip_serializing_if = "Option::is_none")]
    pub probability_of_precipitation: Option<String>,
    #[serde(rename = "probability_of_thunder", skip_serializing_if = "Option::is_none")]
    pub probability_of_thunder: Option<String>,
    #[serde(rename = "relative_humidity", skip_serializing_if = "Option::is_none")]
    pub relative_humidity: Option<String>,
    #[serde(rename = "ultraviolet_index_clear_sky_max", skip_serializing_if = "Option::is_none")]
    pub ultraviolet_index_clear_sky_max: Option<String>,
    #[serde(rename = "wind_from_direction", skip_serializing_if = "Option::is_none")]
    pub wind_from_direction: Option<String>,
    #[serde(rename = "wind_speed", skip_serializing_if = "Option::is_none")]
    pub wind_speed: Option<String>,
    #[serde(rename = "wind_speed_of_gust", skip_serializing_if = "Option::is_none")]
    pub wind_speed_of_gust: Option<String>,
}

impl ForecastUnits {
    pub fn new() -> ForecastUnits {
        ForecastUnits {
            air_pressure_at_sea_level: None,
            air_temperature: None,
            air_temperature_max: None,
            air_temperature_min: None,
            cloud_area_fraction: None,
            cloud_area_fraction_high: None,
            cloud_area_fraction_low: None,
            cloud_area_fraction_medium: None,
            dew_point_temperature: None,
            fog_area_fraction: None,
            precipitation_amount: None,
            precipitation_amount_max: None,
            precipitation_amount_min: None,
            probability_of_precipitation: None,
            probability_of_thunder: None,
            relative_humidity: None,
            ultraviolet_index_clear_sky_max: None,
            wind_from_direction: None,
            wind_speed: None,
            wind_speed_of_gust: None,
        }
    }
}

