/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForecastTimeStepDataNext1Hours : Parameters with validity times over one hour. Will not exist for all time steps.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastTimeStepDataNext1Hours {
    #[serde(rename = "details")]
    pub details: Box<models::ForecastTimePeriod>,
    #[serde(rename = "summary")]
    pub summary: Box<models::ForecastSummary>,
}

impl ForecastTimeStepDataNext1Hours {
    /// Parameters with validity times over one hour. Will not exist for all time steps.
    pub fn new(details: models::ForecastTimePeriod, summary: models::ForecastSummary) -> ForecastTimeStepDataNext1Hours {
        ForecastTimeStepDataNext1Hours {
            details: Box::new(details),
            summary: Box::new(summary),
        }
    }
}

