/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForecastSummary : Summary of weather conditions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastSummary {
    #[serde(rename = "symbol_code")]
    pub symbol_code: models::WeatherSymbol,
}

impl ForecastSummary {
    /// Summary of weather conditions.
    pub fn new(symbol_code: models::WeatherSymbol) -> ForecastSummary {
        ForecastSummary {
            symbol_code,
        }
    }
}

