/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Forecast {
    #[serde(rename = "meta")]
    pub meta: Box<models::ForecastMeta>,
    #[serde(rename = "timeseries")]
    pub timeseries: Vec<models::ForecastTimeStep>,
}

impl Forecast {
    pub fn new(meta: models::ForecastMeta, timeseries: Vec<models::ForecastTimeStep>) -> Forecast {
        Forecast {
            meta: Box::new(meta),
            timeseries,
        }
    }
}

