/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetjsonForecast {
    #[serde(rename = "geometry")]
    pub geometry: Box<models::PointGeometry>,
    #[serde(rename = "properties")]
    pub properties: Box<models::Forecast>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MetjsonForecast {
    pub fn new(geometry: models::PointGeometry, properties: models::Forecast, r#type: Type) -> MetjsonForecast {
        MetjsonForecast {
            geometry: Box::new(geometry),
            properties: Box::new(properties),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Feature")]
    Feature,
}

impl Default for Type {
    fn default() -> Type {
        Self::Feature
    }
}

