/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PointGeometry {
    /// [longitude, latitude, altitude]. All numbers in decimal.
    #[serde(rename = "coordinates")]
    pub coordinates: Vec<f64>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl PointGeometry {
    pub fn new(coordinates: Vec<f64>, r#type: Type) -> PointGeometry {
        PointGeometry {
            coordinates,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Point")]
    Point,
}

impl Default for Type {
    fn default() -> Type {
        Self::Point
    }
}

