/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WeatherSymbol : A identifier that sums up the weather condition for this time period, see documentation.
/// A identifier that sums up the weather condition for this time period, see documentation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WeatherSymbol {
    #[serde(rename = "clearsky_day")]
    ClearskyDay,
    #[serde(rename = "clearsky_night")]
    ClearskyNight,
    #[serde(rename = "clearsky_polartwilight")]
    ClearskyPolartwilight,
    #[serde(rename = "fair_day")]
    FairDay,
    #[serde(rename = "fair_night")]
    FairNight,
    #[serde(rename = "fair_polartwilight")]
    FairPolartwilight,
    #[serde(rename = "lightssnowshowersandthunder_day")]
    LightssnowshowersandthunderDay,
    #[serde(rename = "lightssnowshowersandthunder_night")]
    LightssnowshowersandthunderNight,
    #[serde(rename = "lightssnowshowersandthunder_polartwilight")]
    LightssnowshowersandthunderPolartwilight,
    #[serde(rename = "lightsnowshowers_day")]
    LightsnowshowersDay,
    #[serde(rename = "lightsnowshowers_night")]
    LightsnowshowersNight,
    #[serde(rename = "lightsnowshowers_polartwilight")]
    LightsnowshowersPolartwilight,
    #[serde(rename = "heavyrainandthunder")]
    Heavyrainandthunder,
    #[serde(rename = "heavysnowandthunder")]
    Heavysnowandthunder,
    #[serde(rename = "rainandthunder")]
    Rainandthunder,
    #[serde(rename = "heavysleetshowersandthunder_day")]
    HeavysleetshowersandthunderDay,
    #[serde(rename = "heavysleetshowersandthunder_night")]
    HeavysleetshowersandthunderNight,
    #[serde(rename = "heavysleetshowersandthunder_polartwilight")]
    HeavysleetshowersandthunderPolartwilight,
    #[serde(rename = "heavysnow")]
    Heavysnow,
    #[serde(rename = "heavyrainshowers_day")]
    HeavyrainshowersDay,
    #[serde(rename = "heavyrainshowers_night")]
    HeavyrainshowersNight,
    #[serde(rename = "heavyrainshowers_polartwilight")]
    HeavyrainshowersPolartwilight,
    #[serde(rename = "lightsleet")]
    Lightsleet,
    #[serde(rename = "heavyrain")]
    Heavyrain,
    #[serde(rename = "lightrainshowers_day")]
    LightrainshowersDay,
    #[serde(rename = "lightrainshowers_night")]
    LightrainshowersNight,
    #[serde(rename = "lightrainshowers_polartwilight")]
    LightrainshowersPolartwilight,
    #[serde(rename = "heavysleetshowers_day")]
    HeavysleetshowersDay,
    #[serde(rename = "heavysleetshowers_night")]
    HeavysleetshowersNight,
    #[serde(rename = "heavysleetshowers_polartwilight")]
    HeavysleetshowersPolartwilight,
    #[serde(rename = "lightsleetshowers_day")]
    LightsleetshowersDay,
    #[serde(rename = "lightsleetshowers_night")]
    LightsleetshowersNight,
    #[serde(rename = "lightsleetshowers_polartwilight")]
    LightsleetshowersPolartwilight,
    #[serde(rename = "snow")]
    Snow,
    #[serde(rename = "heavyrainshowersandthunder_day")]
    HeavyrainshowersandthunderDay,
    #[serde(rename = "heavyrainshowersandthunder_night")]
    HeavyrainshowersandthunderNight,
    #[serde(rename = "heavyrainshowersandthunder_polartwilight")]
    HeavyrainshowersandthunderPolartwilight,
    #[serde(rename = "snowshowers_day")]
    SnowshowersDay,
    #[serde(rename = "snowshowers_night")]
    SnowshowersNight,
    #[serde(rename = "snowshowers_polartwilight")]
    SnowshowersPolartwilight,
    #[serde(rename = "fog")]
    Fog,
    #[serde(rename = "snowshowersandthunder_day")]
    SnowshowersandthunderDay,
    #[serde(rename = "snowshowersandthunder_night")]
    SnowshowersandthunderNight,
    #[serde(rename = "snowshowersandthunder_polartwilight")]
    SnowshowersandthunderPolartwilight,
    #[serde(rename = "lightsnowandthunder")]
    Lightsnowandthunder,
    #[serde(rename = "heavysleetandthunder")]
    Heavysleetandthunder,
    #[serde(rename = "lightrain")]
    Lightrain,
    #[serde(rename = "rainshowersandthunder_day")]
    RainshowersandthunderDay,
    #[serde(rename = "rainshowersandthunder_night")]
    RainshowersandthunderNight,
    #[serde(rename = "rainshowersandthunder_polartwilight")]
    RainshowersandthunderPolartwilight,
    #[serde(rename = "rain")]
    Rain,
    #[serde(rename = "lightsnow")]
    Lightsnow,
    #[serde(rename = "lightrainshowersandthunder_day")]
    LightrainshowersandthunderDay,
    #[serde(rename = "lightrainshowersandthunder_night")]
    LightrainshowersandthunderNight,
    #[serde(rename = "lightrainshowersandthunder_polartwilight")]
    LightrainshowersandthunderPolartwilight,
    #[serde(rename = "heavysleet")]
    Heavysleet,
    #[serde(rename = "sleetandthunder")]
    Sleetandthunder,
    #[serde(rename = "lightrainandthunder")]
    Lightrainandthunder,
    #[serde(rename = "sleet")]
    Sleet,
    #[serde(rename = "lightssleetshowersandthunder_day")]
    LightssleetshowersandthunderDay,
    #[serde(rename = "lightssleetshowersandthunder_night")]
    LightssleetshowersandthunderNight,
    #[serde(rename = "lightssleetshowersandthunder_polartwilight")]
    LightssleetshowersandthunderPolartwilight,
    #[serde(rename = "lightsleetandthunder")]
    Lightsleetandthunder,
    #[serde(rename = "partlycloudy_day")]
    PartlycloudyDay,
    #[serde(rename = "partlycloudy_night")]
    PartlycloudyNight,
    #[serde(rename = "partlycloudy_polartwilight")]
    PartlycloudyPolartwilight,
    #[serde(rename = "sleetshowersandthunder_day")]
    SleetshowersandthunderDay,
    #[serde(rename = "sleetshowersandthunder_night")]
    SleetshowersandthunderNight,
    #[serde(rename = "sleetshowersandthunder_polartwilight")]
    SleetshowersandthunderPolartwilight,
    #[serde(rename = "rainshowers_day")]
    RainshowersDay,
    #[serde(rename = "rainshowers_night")]
    RainshowersNight,
    #[serde(rename = "rainshowers_polartwilight")]
    RainshowersPolartwilight,
    #[serde(rename = "snowandthunder")]
    Snowandthunder,
    #[serde(rename = "sleetshowers_day")]
    SleetshowersDay,
    #[serde(rename = "sleetshowers_night")]
    SleetshowersNight,
    #[serde(rename = "sleetshowers_polartwilight")]
    SleetshowersPolartwilight,
    #[serde(rename = "cloudy")]
    Cloudy,
    #[serde(rename = "heavysnowshowersandthunder_day")]
    HeavysnowshowersandthunderDay,
    #[serde(rename = "heavysnowshowersandthunder_night")]
    HeavysnowshowersandthunderNight,
    #[serde(rename = "heavysnowshowersandthunder_polartwilight")]
    HeavysnowshowersandthunderPolartwilight,
    #[serde(rename = "heavysnowshowers_day")]
    HeavysnowshowersDay,
    #[serde(rename = "heavysnowshowers_night")]
    HeavysnowshowersNight,
    #[serde(rename = "heavysnowshowers_polartwilight")]
    HeavysnowshowersPolartwilight,

}

impl std::fmt::Display for WeatherSymbol {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ClearskyDay => write!(f, "clearsky_day"),
            Self::ClearskyNight => write!(f, "clearsky_night"),
            Self::ClearskyPolartwilight => write!(f, "clearsky_polartwilight"),
            Self::FairDay => write!(f, "fair_day"),
            Self::FairNight => write!(f, "fair_night"),
            Self::FairPolartwilight => write!(f, "fair_polartwilight"),
            Self::LightssnowshowersandthunderDay => write!(f, "lightssnowshowersandthunder_day"),
            Self::LightssnowshowersandthunderNight => write!(f, "lightssnowshowersandthunder_night"),
            Self::LightssnowshowersandthunderPolartwilight => write!(f, "lightssnowshowersandthunder_polartwilight"),
            Self::LightsnowshowersDay => write!(f, "lightsnowshowers_day"),
            Self::LightsnowshowersNight => write!(f, "lightsnowshowers_night"),
            Self::LightsnowshowersPolartwilight => write!(f, "lightsnowshowers_polartwilight"),
            Self::Heavyrainandthunder => write!(f, "heavyrainandthunder"),
            Self::Heavysnowandthunder => write!(f, "heavysnowandthunder"),
            Self::Rainandthunder => write!(f, "rainandthunder"),
            Self::HeavysleetshowersandthunderDay => write!(f, "heavysleetshowersandthunder_day"),
            Self::HeavysleetshowersandthunderNight => write!(f, "heavysleetshowersandthunder_night"),
            Self::HeavysleetshowersandthunderPolartwilight => write!(f, "heavysleetshowersandthunder_polartwilight"),
            Self::Heavysnow => write!(f, "heavysnow"),
            Self::HeavyrainshowersDay => write!(f, "heavyrainshowers_day"),
            Self::HeavyrainshowersNight => write!(f, "heavyrainshowers_night"),
            Self::HeavyrainshowersPolartwilight => write!(f, "heavyrainshowers_polartwilight"),
            Self::Lightsleet => write!(f, "lightsleet"),
            Self::Heavyrain => write!(f, "heavyrain"),
            Self::LightrainshowersDay => write!(f, "lightrainshowers_day"),
            Self::LightrainshowersNight => write!(f, "lightrainshowers_night"),
            Self::LightrainshowersPolartwilight => write!(f, "lightrainshowers_polartwilight"),
            Self::HeavysleetshowersDay => write!(f, "heavysleetshowers_day"),
            Self::HeavysleetshowersNight => write!(f, "heavysleetshowers_night"),
            Self::HeavysleetshowersPolartwilight => write!(f, "heavysleetshowers_polartwilight"),
            Self::LightsleetshowersDay => write!(f, "lightsleetshowers_day"),
            Self::LightsleetshowersNight => write!(f, "lightsleetshowers_night"),
            Self::LightsleetshowersPolartwilight => write!(f, "lightsleetshowers_polartwilight"),
            Self::Snow => write!(f, "snow"),
            Self::HeavyrainshowersandthunderDay => write!(f, "heavyrainshowersandthunder_day"),
            Self::HeavyrainshowersandthunderNight => write!(f, "heavyrainshowersandthunder_night"),
            Self::HeavyrainshowersandthunderPolartwilight => write!(f, "heavyrainshowersandthunder_polartwilight"),
            Self::SnowshowersDay => write!(f, "snowshowers_day"),
            Self::SnowshowersNight => write!(f, "snowshowers_night"),
            Self::SnowshowersPolartwilight => write!(f, "snowshowers_polartwilight"),
            Self::Fog => write!(f, "fog"),
            Self::SnowshowersandthunderDay => write!(f, "snowshowersandthunder_day"),
            Self::SnowshowersandthunderNight => write!(f, "snowshowersandthunder_night"),
            Self::SnowshowersandthunderPolartwilight => write!(f, "snowshowersandthunder_polartwilight"),
            Self::Lightsnowandthunder => write!(f, "lightsnowandthunder"),
            Self::Heavysleetandthunder => write!(f, "heavysleetandthunder"),
            Self::Lightrain => write!(f, "lightrain"),
            Self::RainshowersandthunderDay => write!(f, "rainshowersandthunder_day"),
            Self::RainshowersandthunderNight => write!(f, "rainshowersandthunder_night"),
            Self::RainshowersandthunderPolartwilight => write!(f, "rainshowersandthunder_polartwilight"),
            Self::Rain => write!(f, "rain"),
            Self::Lightsnow => write!(f, "lightsnow"),
            Self::LightrainshowersandthunderDay => write!(f, "lightrainshowersandthunder_day"),
            Self::LightrainshowersandthunderNight => write!(f, "lightrainshowersandthunder_night"),
            Self::LightrainshowersandthunderPolartwilight => write!(f, "lightrainshowersandthunder_polartwilight"),
            Self::Heavysleet => write!(f, "heavysleet"),
            Self::Sleetandthunder => write!(f, "sleetandthunder"),
            Self::Lightrainandthunder => write!(f, "lightrainandthunder"),
            Self::Sleet => write!(f, "sleet"),
            Self::LightssleetshowersandthunderDay => write!(f, "lightssleetshowersandthunder_day"),
            Self::LightssleetshowersandthunderNight => write!(f, "lightssleetshowersandthunder_night"),
            Self::LightssleetshowersandthunderPolartwilight => write!(f, "lightssleetshowersandthunder_polartwilight"),
            Self::Lightsleetandthunder => write!(f, "lightsleetandthunder"),
            Self::PartlycloudyDay => write!(f, "partlycloudy_day"),
            Self::PartlycloudyNight => write!(f, "partlycloudy_night"),
            Self::PartlycloudyPolartwilight => write!(f, "partlycloudy_polartwilight"),
            Self::SleetshowersandthunderDay => write!(f, "sleetshowersandthunder_day"),
            Self::SleetshowersandthunderNight => write!(f, "sleetshowersandthunder_night"),
            Self::SleetshowersandthunderPolartwilight => write!(f, "sleetshowersandthunder_polartwilight"),
            Self::RainshowersDay => write!(f, "rainshowers_day"),
            Self::RainshowersNight => write!(f, "rainshowers_night"),
            Self::RainshowersPolartwilight => write!(f, "rainshowers_polartwilight"),
            Self::Snowandthunder => write!(f, "snowandthunder"),
            Self::SleetshowersDay => write!(f, "sleetshowers_day"),
            Self::SleetshowersNight => write!(f, "sleetshowers_night"),
            Self::SleetshowersPolartwilight => write!(f, "sleetshowers_polartwilight"),
            Self::Cloudy => write!(f, "cloudy"),
            Self::HeavysnowshowersandthunderDay => write!(f, "heavysnowshowersandthunder_day"),
            Self::HeavysnowshowersandthunderNight => write!(f, "heavysnowshowersandthunder_night"),
            Self::HeavysnowshowersandthunderPolartwilight => write!(f, "heavysnowshowersandthunder_polartwilight"),
            Self::HeavysnowshowersDay => write!(f, "heavysnowshowers_day"),
            Self::HeavysnowshowersNight => write!(f, "heavysnowshowers_night"),
            Self::HeavysnowshowersPolartwilight => write!(f, "heavysnowshowers_polartwilight"),
        }
    }
}

impl Default for WeatherSymbol {
    fn default() -> WeatherSymbol {
        Self::ClearskyDay
    }
}

