use serde::Deserialize;
use serde::Serialize;

// Disable dead code warning - we are not concerned about not instantiating all of the structs
#[allow(dead_code)]
// This has been generated by this nice tool:
// https://transform.tools/json-to-rust-serde
#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GeoJsonResponse {
    #[serde(rename = "type")]
    pub type_field: String,
    pub bbox: Vec<f64>,
    pub features: Vec<Feature>,
    pub metadata: Metadata,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Feature {
    pub bbox: Vec<f64>,
    #[serde(rename = "type")]
    pub type_field: String,
    pub properties: Properties,
    pub geometry: Geometry,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Properties {
    pub segments: Vec<Segment>,
    pub extras: Option<Extras>,
    pub warnings: Option<Vec<Warning>>,
    #[serde(rename = "way_points")]
    pub way_points: Vec<i64>,
    pub summary: Summary2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Segment {
    pub distance: f64,
    pub duration: f64,
    pub steps: Vec<Step>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Step {
    pub distance: f64,
    pub duration: f64,
    #[serde(rename = "type")]
    pub type_field: i64,
    pub instruction: String,
    pub name: String,
    #[serde(rename = "way_points")]
    pub way_points: Vec<i64>,
    #[serde(rename = "exit_number")]
    pub exit_number: Option<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Extras {
    pub roadaccessrestrictions: Roadaccessrestrictions,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Roadaccessrestrictions {
    pub values: Vec<Vec<i64>>,
    pub summary: Vec<Summary>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Summary {
    pub value: f64,
    pub distance: f64,
    pub amount: f64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Warning {
    pub code: i64,
    pub message: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Summary2 {
    pub distance: f64,
    pub duration: f64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Geometry {
    pub coordinates: Vec<Vec<f64>>,
    #[serde(rename = "type")]
    pub type_field: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Metadata {
    pub attribution: String,
    pub service: String,
    pub timestamp: i64,
    pub query: Query,
    pub engine: Engine,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Query {
    pub coordinates: Vec<Vec<f64>>,
    pub profile: String,
    pub profile_name: String,
    pub format: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Engine {
    pub version: String,
    #[serde(rename = "build_date")]
    pub build_date: String,
    #[serde(rename = "graph_date")]
    pub graph_date: String,
    #[serde(rename = "osm_date")]
    pub osm_date: String,
}
