/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`elevation_line_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ElevationLinePostError {
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status500(serde_json::Value),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`elevation_point_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ElevationPointGetError {
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status500(serde_json::Value),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`elevation_point_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ElevationPointPostError {
    Status401(serde_json::Value),
    Status403(serde_json::Value),
    Status500(serde_json::Value),
    UnknownValue(serde_json::Value),
}


/// This endpoint can take planar 2D line objects and enrich them with elevation from a variety of datasets.  The input and output formats are:   * GeoJSON   * Polyline   * <a href=\"https://developers.google.com/maps/documentation/utilities/polylinealgorithm\">Google's Encoded polyline</a> with coordinate precision 5 or 6  Example: ```   # POST LineString as polyline   curl -XPOST https://api.openrouteservice.org/elevation/line     -H 'Content-Type: application/json' \\     -H 'Authorization: INSERT_YOUR_KEY     -d '{       \"format_in\": \"polyline\",       \"format_out\": \"encodedpolyline5\",       \"geometry\": [[13.349762, 38.112952],                    [12.638397, 37.645772]]         }' ``` 
pub async fn elevation_line_post(configuration: &configuration::Configuration, body: models::ElevationLinePostRequest) -> Result<models::ElevationLinePost200Response, Error<ElevationLinePostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_body = body;

    let uri_str = format!("{}/elevation/line", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ElevationLinePost200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ElevationLinePost200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ElevationLinePostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// This endpoint can take a 2D point and enrich it with elevation from a variety of datasets.  The output formats are:   * GeoJSON   * Point  Example: ```   # GET point   curl -XGET https://localhost:5000/elevation/point?geometry=13.349762,38.11295 ``` 
pub async fn elevation_point_get(configuration: &configuration::Configuration, api_key: &str, geometry: Vec<f64>, format_out: Option<&str>, dataset: Option<&str>) -> Result<models::ElevationPointGet200Response, Error<ElevationPointGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_api_key = api_key;
    let p_query_geometry = geometry;
    let p_query_format_out = format_out;
    let p_query_dataset = dataset;

    let uri_str = format!("{}/elevation/point", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("api_key", &p_query_api_key.to_string())]);
    req_builder = match "csv" {
        "multi" => req_builder.query(&p_query_geometry.into_iter().map(|p| ("geometry".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("geometry", &p_query_geometry.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_format_out {
        req_builder = req_builder.query(&[("format_out", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_dataset {
        req_builder = req_builder.query(&[("dataset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ElevationPointGet200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ElevationPointGet200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ElevationPointGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// This endpoint can take a 2D point and enrich it with elevation from a variety of datasets.  The input and output formats are:   * GeoJSON   * Point  Example: ```   # POST point as GeoJSON   # https://api.openrouteservice.org/elevation/point?api_key=YOUR-KEY   {     \"format_in\": \"geojson\",     \"format_out\": \"geojson\",     \"geometry\": {       \"coordinates\": [13.349762, 38.11295],       \"type\": \"Point\"     }   } ``` 
pub async fn elevation_point_post(configuration: &configuration::Configuration, body: models::ElevationPointPostRequest) -> Result<models::ElevationPointGet200Response, Error<ElevationPointPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_body = body;

    let uri_str = format!("{}/elevation/point", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ElevationPointGet200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ElevationPointGet200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ElevationPointPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

