/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`geocode_autocomplete_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GeocodeAutocompleteGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`geocode_reverse_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GeocodeReverseGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`geocode_search_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GeocodeSearchGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`geocode_search_structured_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GeocodeSearchStructuredGetError {
    UnknownValue(serde_json::Value),
}


/// **Requests should be throttled when using this endpoint!** *Be aware that Responses are asynchronous.* Returns a JSON formatted list of objects corresponding to the search input. `boundary.*`-parameters can be combined if they are overlapping. **The interactivity for this enpoint is experimental!** [Please refer to this external Documentation](https://github.com/pelias/documentation/blob/master/autocomplete.md) 
pub async fn geocode_autocomplete_get(configuration: &configuration::Configuration, api_key: &str, text: &str, focus_point_lon: Option<f32>, focus_point_lat: Option<f32>, boundary_rect_min_lon: Option<f32>, boundary_rect_min_lat: Option<f32>, boundary_rect_max_lon: Option<f32>, boundary_rect_max_lat: Option<f32>, boundary_country: Option<&str>, sources: Option<Vec<String>>, layers: Option<Vec<String>>) -> Result<models::GeocodeResponse, Error<GeocodeAutocompleteGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_api_key = api_key;
    let p_query_text = text;
    let p_query_focus_point_lon = focus_point_lon;
    let p_query_focus_point_lat = focus_point_lat;
    let p_query_boundary_rect_min_lon = boundary_rect_min_lon;
    let p_query_boundary_rect_min_lat = boundary_rect_min_lat;
    let p_query_boundary_rect_max_lon = boundary_rect_max_lon;
    let p_query_boundary_rect_max_lat = boundary_rect_max_lat;
    let p_query_boundary_country = boundary_country;
    let p_query_sources = sources;
    let p_query_layers = layers;

    let uri_str = format!("{}/geocode/autocomplete", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("api_key", &p_query_api_key.to_string())]);
    req_builder = req_builder.query(&[("text", &p_query_text.to_string())]);
    if let Some(ref param_value) = p_query_focus_point_lon {
        req_builder = req_builder.query(&[("focus.point.lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_focus_point_lat {
        req_builder = req_builder.query(&[("focus.point.lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_min_lon {
        req_builder = req_builder.query(&[("boundary.rect.min_lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_min_lat {
        req_builder = req_builder.query(&[("boundary.rect.min_lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_max_lon {
        req_builder = req_builder.query(&[("boundary.rect.max_lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_max_lat {
        req_builder = req_builder.query(&[("boundary.rect.max_lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_country {
        req_builder = req_builder.query(&[("boundary.country", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sources {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("sources".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("sources", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_layers {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("layers".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("layers", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GeocodeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GeocodeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GeocodeAutocompleteGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns the next enclosing object with an address tag which surrounds the given coordinate. **The interactivity for this enpoint is experimental!** [Please refer to this external Documentation](https://github.com/pelias/documentation/blob/master/reverse.md#reverse-geocoding) 
pub async fn geocode_reverse_get(configuration: &configuration::Configuration, api_key: &str, point_lon: f32, point_lat: f32, boundary_circle_radius: Option<f64>, size: Option<i64>, layers: Option<Vec<String>>, sources: Option<Vec<String>>, boundary_country: Option<&str>) -> Result<models::GeocodeResponse, Error<GeocodeReverseGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_api_key = api_key;
    let p_query_point_lon = point_lon;
    let p_query_point_lat = point_lat;
    let p_query_boundary_circle_radius = boundary_circle_radius;
    let p_query_size = size;
    let p_query_layers = layers;
    let p_query_sources = sources;
    let p_query_boundary_country = boundary_country;

    let uri_str = format!("{}/geocode/reverse", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("api_key", &p_query_api_key.to_string())]);
    req_builder = req_builder.query(&[("point.lon", &p_query_point_lon.to_string())]);
    req_builder = req_builder.query(&[("point.lat", &p_query_point_lat.to_string())]);
    if let Some(ref param_value) = p_query_boundary_circle_radius {
        req_builder = req_builder.query(&[("boundary.circle.radius", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_layers {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("layers".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("layers", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_sources {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("sources".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("sources", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_boundary_country {
        req_builder = req_builder.query(&[("boundary.country", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GeocodeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GeocodeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GeocodeReverseGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a JSON formatted list of objects corresponding to the search input. `boundary.*`-parameters can be combined if they are overlapping. **The interactivity for this enpoint is experimental!** [Please refer to this external Documentation](https://github.com/pelias/documentation/blob/master/search.md#search-the-world) 
pub async fn geocode_search_get(configuration: &configuration::Configuration, api_key: &str, text: &str, focus_point_lon: Option<f32>, focus_point_lat: Option<f32>, boundary_rect_min_lon: Option<f32>, boundary_rect_min_lat: Option<f32>, boundary_rect_max_lon: Option<f32>, boundary_rect_max_lat: Option<f32>, boundary_circle_lon: Option<f32>, boundary_circle_lat: Option<f32>, boundary_circle_radius: Option<f32>, boundary_gid: Option<&str>, boundary_country: Option<&str>, sources: Option<Vec<String>>, layers: Option<Vec<String>>, size: Option<i64>) -> Result<models::GeocodeResponse, Error<GeocodeSearchGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_api_key = api_key;
    let p_query_text = text;
    let p_query_focus_point_lon = focus_point_lon;
    let p_query_focus_point_lat = focus_point_lat;
    let p_query_boundary_rect_min_lon = boundary_rect_min_lon;
    let p_query_boundary_rect_min_lat = boundary_rect_min_lat;
    let p_query_boundary_rect_max_lon = boundary_rect_max_lon;
    let p_query_boundary_rect_max_lat = boundary_rect_max_lat;
    let p_query_boundary_circle_lon = boundary_circle_lon;
    let p_query_boundary_circle_lat = boundary_circle_lat;
    let p_query_boundary_circle_radius = boundary_circle_radius;
    let p_query_boundary_gid = boundary_gid;
    let p_query_boundary_country = boundary_country;
    let p_query_sources = sources;
    let p_query_layers = layers;
    let p_query_size = size;

    let uri_str = format!("{}/geocode/search", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("api_key", &p_query_api_key.to_string())]);
    req_builder = req_builder.query(&[("text", &p_query_text.to_string())]);
    if let Some(ref param_value) = p_query_focus_point_lon {
        req_builder = req_builder.query(&[("focus.point.lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_focus_point_lat {
        req_builder = req_builder.query(&[("focus.point.lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_min_lon {
        req_builder = req_builder.query(&[("boundary.rect.min_lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_min_lat {
        req_builder = req_builder.query(&[("boundary.rect.min_lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_max_lon {
        req_builder = req_builder.query(&[("boundary.rect.max_lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_max_lat {
        req_builder = req_builder.query(&[("boundary.rect.max_lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_circle_lon {
        req_builder = req_builder.query(&[("boundary.circle.lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_circle_lat {
        req_builder = req_builder.query(&[("boundary.circle.lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_circle_radius {
        req_builder = req_builder.query(&[("boundary.circle.radius", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_gid {
        req_builder = req_builder.query(&[("boundary.gid", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_country {
        req_builder = req_builder.query(&[("boundary.country", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sources {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("sources".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("sources", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_layers {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("layers".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("layers", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GeocodeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GeocodeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GeocodeSearchGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a JSON formatted list of objects corresponding to the search input. **The interactivity for this enpoint is experimental!** [Please refer to this external Documentation](https://github.com/pelias/documentation/blob/master/structured-geocoding.md#structured-geocoding) 
pub async fn geocode_search_structured_get(configuration: &configuration::Configuration, api_key: &str, address: Option<&str>, neighbourhood: Option<&str>, country: Option<&str>, postalcode: Option<&str>, region: Option<&str>, county: Option<&str>, locality: Option<&str>, borough: Option<&str>, focus_point_lon: Option<f32>, focus_point_lat: Option<f32>, boundary_rect_min_lon: Option<f32>, boundary_rect_min_lat: Option<f32>, boundary_rect_max_lon: Option<f32>, boundary_rect_max_lat: Option<f32>, boundary_circle_lon: Option<f32>, boundary_circle_lat: Option<f32>, boundary_circle_radius: Option<f32>, boundary_country: Option<&str>, layers: Option<Vec<String>>, sources: Option<Vec<String>>, size: Option<i64>) -> Result<models::GeocodeResponse, Error<GeocodeSearchStructuredGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_api_key = api_key;
    let p_query_address = address;
    let p_query_neighbourhood = neighbourhood;
    let p_query_country = country;
    let p_query_postalcode = postalcode;
    let p_query_region = region;
    let p_query_county = county;
    let p_query_locality = locality;
    let p_query_borough = borough;
    let p_query_focus_point_lon = focus_point_lon;
    let p_query_focus_point_lat = focus_point_lat;
    let p_query_boundary_rect_min_lon = boundary_rect_min_lon;
    let p_query_boundary_rect_min_lat = boundary_rect_min_lat;
    let p_query_boundary_rect_max_lon = boundary_rect_max_lon;
    let p_query_boundary_rect_max_lat = boundary_rect_max_lat;
    let p_query_boundary_circle_lon = boundary_circle_lon;
    let p_query_boundary_circle_lat = boundary_circle_lat;
    let p_query_boundary_circle_radius = boundary_circle_radius;
    let p_query_boundary_country = boundary_country;
    let p_query_layers = layers;
    let p_query_sources = sources;
    let p_query_size = size;

    let uri_str = format!("{}/geocode/search/structured", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("api_key", &p_query_api_key.to_string())]);
    if let Some(ref param_value) = p_query_address {
        req_builder = req_builder.query(&[("address", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_neighbourhood {
        req_builder = req_builder.query(&[("neighbourhood", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_country {
        req_builder = req_builder.query(&[("country", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_postalcode {
        req_builder = req_builder.query(&[("postalcode", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_region {
        req_builder = req_builder.query(&[("region", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_county {
        req_builder = req_builder.query(&[("county", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_locality {
        req_builder = req_builder.query(&[("locality", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_borough {
        req_builder = req_builder.query(&[("borough", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_focus_point_lon {
        req_builder = req_builder.query(&[("focus.point.lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_focus_point_lat {
        req_builder = req_builder.query(&[("focus.point.lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_min_lon {
        req_builder = req_builder.query(&[("boundary.rect.min_lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_min_lat {
        req_builder = req_builder.query(&[("boundary.rect.min_lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_max_lon {
        req_builder = req_builder.query(&[("boundary.rect.max_lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_rect_max_lat {
        req_builder = req_builder.query(&[("boundary.rect.max_lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_circle_lon {
        req_builder = req_builder.query(&[("boundary.circle.lon", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_circle_lat {
        req_builder = req_builder.query(&[("boundary.circle.lat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_circle_radius {
        req_builder = req_builder.query(&[("boundary.circle.radius", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_boundary_country {
        req_builder = req_builder.query(&[("boundary.country", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_layers {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("layers".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("layers", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_sources {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("sources".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("sources", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GeocodeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GeocodeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GeocodeSearchStructuredGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

