/*
 * Locationforecast
 *
 * Weather forecasts for any location on earth
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`classic_format_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClassicFormatGetError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(),
    Status429(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`classic_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClassicGetError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(),
    Status429(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`compact_format_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompactFormatGetError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(),
    Status429(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`compact_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompactGetError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(),
    Status429(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`complete_format_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompleteFormatGetError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(),
    Status429(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`complete_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompleteGetError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(),
    Status429(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`status_format_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatusFormatGetError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(),
    Status429(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`status_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatusGetError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status422(),
    Status429(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}


/// Weather forecasts for any location on earth
pub async fn classic_format_get(configuration: &configuration::Configuration, lat: f32, lon: f32, format: &str, altitude: Option<i32>) -> Result<String, Error<ClassicFormatGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_lat = lat;
    let p_query_lon = lon;
    let p_path_format = format;
    let p_query_altitude = altitude;

    let uri_str = format!("{}/classic.{format}", configuration.base_path, format=crate::apis::urlencode(p_path_format));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_altitude {
        req_builder = req_builder.query(&[("altitude", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("lat", &p_query_lat.to_string())]);
    req_builder = req_builder.query(&[("lon", &p_query_lon.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClassicFormatGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Weather forecasts for any location on earth
pub async fn classic_get(configuration: &configuration::Configuration, lat: f32, lon: f32, altitude: Option<i32>) -> Result<String, Error<ClassicGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_lat = lat;
    let p_query_lon = lon;
    let p_query_altitude = altitude;

    let uri_str = format!("{}/classic", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_altitude {
        req_builder = req_builder.query(&[("altitude", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("lat", &p_query_lat.to_string())]);
    req_builder = req_builder.query(&[("lon", &p_query_lon.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClassicGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Weather forecasts for any location on earth
pub async fn compact_format_get(configuration: &configuration::Configuration, lat: f32, lon: f32, format: &str, altitude: Option<i32>) -> Result<models::MetjsonForecast, Error<CompactFormatGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_lat = lat;
    let p_query_lon = lon;
    let p_path_format = format;
    let p_query_altitude = altitude;

    let uri_str = format!("{}/compact.{format}", configuration.base_path, format=crate::apis::urlencode(p_path_format));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_altitude {
        req_builder = req_builder.query(&[("altitude", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("lat", &p_query_lat.to_string())]);
    req_builder = req_builder.query(&[("lon", &p_query_lon.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MetjsonForecast`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MetjsonForecast`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompactFormatGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Weather forecasts for any location on earth
pub async fn compact_get(configuration: &configuration::Configuration, lat: f32, lon: f32, altitude: Option<i32>) -> Result<models::MetjsonForecast, Error<CompactGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_lat = lat;
    let p_query_lon = lon;
    let p_query_altitude = altitude;

    let uri_str = format!("{}/compact", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_altitude {
        req_builder = req_builder.query(&[("altitude", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("lat", &p_query_lat.to_string())]);
    req_builder = req_builder.query(&[("lon", &p_query_lon.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MetjsonForecast`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MetjsonForecast`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompactGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Weather forecasts for any location on earth
pub async fn complete_format_get(configuration: &configuration::Configuration, lat: f32, lon: f32, format: &str, altitude: Option<i32>) -> Result<models::MetjsonForecast, Error<CompleteFormatGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_lat = lat;
    let p_query_lon = lon;
    let p_path_format = format;
    let p_query_altitude = altitude;

    let uri_str = format!("{}/complete.{format}", configuration.base_path, format=crate::apis::urlencode(p_path_format));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_altitude {
        req_builder = req_builder.query(&[("altitude", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("lat", &p_query_lat.to_string())]);
    req_builder = req_builder.query(&[("lon", &p_query_lon.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MetjsonForecast`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MetjsonForecast`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompleteFormatGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Weather forecasts for any location on earth
pub async fn complete_get(configuration: &configuration::Configuration, lat: f32, lon: f32, altitude: Option<i32>) -> Result<models::MetjsonForecast, Error<CompleteGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_lat = lat;
    let p_query_lon = lon;
    let p_query_altitude = altitude;

    let uri_str = format!("{}/complete", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_altitude {
        req_builder = req_builder.query(&[("altitude", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("lat", &p_query_lat.to_string())]);
    req_builder = req_builder.query(&[("lon", &p_query_lon.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MetjsonForecast`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MetjsonForecast`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CompleteGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Weather forecasts for any location on earth
pub async fn status_format_get(configuration: &configuration::Configuration, format: &str) -> Result<String, Error<StatusFormatGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_format = format;

    let uri_str = format!("{}/status.{format}", configuration.base_path, format=crate::apis::urlencode(p_path_format));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatusFormatGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Weather forecasts for any location on earth
pub async fn status_get(configuration: &configuration::Configuration, ) -> Result<String, Error<StatusGetError>> {

    let uri_str = format!("{}/status", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatusGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

