/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElevationPointPostRequest {
    /// The input format the API has to expect.
    #[serde(rename = "format_in")]
    pub format_in: FormatIn,
    /// The output format to be returned.
    #[serde(rename = "format_out", skip_serializing_if = "Option::is_none")]
    pub format_out: Option<FormatOut>,
    /// The elevation dataset to be used.
    #[serde(rename = "dataset", skip_serializing_if = "Option::is_none")]
    pub dataset: Option<Dataset>,
    /// * geojson: A geometry object of a Point GeoJSON, e.g.          {\"type\": \"Point\",           \"coordinates\": [13.331273, 38.10849]          } * point: A coordinate list, e.g.          [13.331273, 38.10849] 
    #[serde(rename = "geometry")]
    pub geometry: serde_json::Value,
}

impl ElevationPointPostRequest {
    pub fn new(format_in: FormatIn, geometry: serde_json::Value) -> ElevationPointPostRequest {
        ElevationPointPostRequest {
            format_in,
            format_out: None,
            dataset: None,
            geometry,
        }
    }
}
/// The input format the API has to expect.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormatIn {
    #[serde(rename = "geojson")]
    Geojson,
    #[serde(rename = "point")]
    Point,
}

impl Default for FormatIn {
    fn default() -> FormatIn {
        Self::Geojson
    }
}
/// The output format to be returned.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormatOut {
    #[serde(rename = "geojson")]
    Geojson,
    #[serde(rename = "point")]
    Point,
}

impl Default for FormatOut {
    fn default() -> FormatOut {
        Self::Geojson
    }
}
/// The elevation dataset to be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Dataset {
    #[serde(rename = "srtm")]
    Srtm,
}

impl Default for Dataset {
    fn default() -> Dataset {
        Self::Srtm
    }
}

