/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElevationLinePostRequest {
    /// The input format the API has to expect.
    #[serde(rename = "format_in")]
    pub format_in: FormatIn,
    /// The output format to be returned.
    #[serde(rename = "format_out", skip_serializing_if = "Option::is_none")]
    pub format_out: Option<FormatOut>,
    /// The elevation dataset to be used.
    #[serde(rename = "dataset", skip_serializing_if = "Option::is_none")]
    pub dataset: Option<Dataset>,
    /// * geojson: A geometry object of a LineString GeoJSON, e.g.          {\"type\": \"LineString\",           \"coordinates\": [[13.331302, 38.108433],[13.331273, 38.10849]]          } * polyline: A list of coordinate lists, e.g.          [[13.331302, 38.108433], [13.331273, 38.10849]]  * encodedpolyline5: A <a href=\"https://developers.google.com/maps/documentation/utilities/polylinealgorithm\">Google encoded polyline</a> with a coordinate precision of 5, e.g.          u`rgFswjpAKD  * encodedpolyline6: A <a href=\"https://developers.google.com/maps/documentation/utilities/polylinealgorithm\">Google encoded polyline</a> with a coordinate precision of 6, e.g.          ap}tgAkutlXqBx@ 
    #[serde(rename = "geometry")]
    pub geometry: serde_json::Value,
}

impl ElevationLinePostRequest {
    pub fn new(format_in: FormatIn, geometry: serde_json::Value) -> ElevationLinePostRequest {
        ElevationLinePostRequest {
            format_in,
            format_out: None,
            dataset: None,
            geometry,
        }
    }
}
/// The input format the API has to expect.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormatIn {
    #[serde(rename = "geojson")]
    Geojson,
    #[serde(rename = "polyline")]
    Polyline,
    #[serde(rename = "encodedpolyline5")]
    Encodedpolyline5,
    #[serde(rename = "encodedpolyline6")]
    Encodedpolyline6,
}

impl Default for FormatIn {
    fn default() -> FormatIn {
        Self::Geojson
    }
}
/// The output format to be returned.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormatOut {
    #[serde(rename = "geojson")]
    Geojson,
    #[serde(rename = "polyline")]
    Polyline,
    #[serde(rename = "encodedpolyline5")]
    Encodedpolyline5,
    #[serde(rename = "encodedpolyline6")]
    Encodedpolyline6,
}

impl Default for FormatOut {
    fn default() -> FormatOut {
        Self::Geojson
    }
}
/// The elevation dataset to be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Dataset {
    #[serde(rename = "srtm")]
    Srtm,
}

impl Default for Dataset {
    fn default() -> Dataset {
        Self::Srtm
    }
}

