/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPost200ResponseRoutesInnerStepsInner {
    /// string that is either `start`, `job` or `end`
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// estimated time of arrival at this step in seconds
    #[serde(rename = "arrival", skip_serializing_if = "Option::is_none")]
    pub arrival: Option<f32>,
    /// cumulated travel time upon arrival at this step in seconds
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f32>,
    /// setup time at this step 
    #[serde(rename = "setup", skip_serializing_if = "Option::is_none")]
    pub setup: Option<f64>,
    /// service time at this step 
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<f64>,
    /// waiting time upon arrival at this step, only provided if `type` value is `job`
    #[serde(rename = "waiting_time", skip_serializing_if = "Option::is_none")]
    pub waiting_time: Option<f32>,
    /// array of violation objects for this step
    #[serde(rename = "violations", skip_serializing_if = "Option::is_none")]
    pub violations: Option<Vec<models::OptimizationPost200ResponseSummaryViolationsInner>>,
    /// step description, if provided in input 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// coordinates array for this step (if provided in input)
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<f32>>,
    /// id of the task performed at this step, only provided if type value is `job`, `pickup`, `delivery` or `break` 
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// vehicle load after step completion (with capacity constraints) 
    #[serde(rename = "load", skip_serializing_if = "Option::is_none")]
    pub load: Option<i32>,
    /// traveled distance upon arrival at this step. Only provided when using the `-g` flag
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f32>,
}

impl OptimizationPost200ResponseRoutesInnerStepsInner {
    pub fn new() -> OptimizationPost200ResponseRoutesInnerStepsInner {
        OptimizationPost200ResponseRoutesInnerStepsInner {
            r#type: None,
            arrival: None,
            duration: None,
            setup: None,
            service: None,
            waiting_time: None,
            violations: None,
            description: None,
            location: None,
            id: None,
            load: None,
            distance: None,
        }
    }
}

