/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPostRequest {
    /// Array of `job` objects describing the places to visit. For a detailed object description visit the [VROOM api description](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#jobs) 
    #[serde(rename = "jobs")]
    pub jobs: Vec<models::OptimizationPostRequestJobsInner>,
    /// Array of `vehicle` objects describing the available vehicles. For a detailed object description visit the [VROOM API description](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#vehicles) 
    #[serde(rename = "vehicles")]
    pub vehicles: Vec<models::OptimizationPostRequestVehiclesInner>,
    #[serde(rename = "matrices", skip_serializing_if = "Option::is_none")]
    pub matrices: Option<Box<models::OptimizationPostRequestMatrices>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::OptimizationPostRequestOptions>>,
}

impl OptimizationPostRequest {
    pub fn new(jobs: Vec<models::OptimizationPostRequestJobsInner>, vehicles: Vec<models::OptimizationPostRequestVehiclesInner>) -> OptimizationPostRequest {
        OptimizationPostRequest {
            jobs,
            vehicles,
            matrices: None,
            options: None,
        }
    }
}

