/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPostRequestVehiclesInnerStepsInner {
    /// step type (either start, job, pickup, delivery, break or end)] 
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// id of the task to be performed at this step if `type` value is not `start` or `end` 
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f64>,
    /// hard constraint on service time (as absolute or relative timestamp) 
    #[serde(rename = "service_at", skip_serializing_if = "Option::is_none")]
    pub service_at: Option<f64>,
    /// hard constraint on service time lower bound (as absolute or relative timestamp) 
    #[serde(rename = "service_after", skip_serializing_if = "Option::is_none")]
    pub service_after: Option<f64>,
    /// hard constraint on service time upper bound (as absolute or relative timestamp) 
    #[serde(rename = "service_before", skip_serializing_if = "Option::is_none")]
    pub service_before: Option<f64>,
}

impl OptimizationPostRequestVehiclesInnerStepsInner {
    pub fn new() -> OptimizationPostRequestVehiclesInnerStepsInner {
        OptimizationPostRequestVehiclesInnerStepsInner {
            r#type: None,
            id: None,
            service_at: None,
            service_after: None,
            service_before: None,
        }
    }
}
/// step type (either start, job, pickup, delivery, break or end)] 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "start")]
    Start,
    #[serde(rename = "job")]
    Job,
    #[serde(rename = "pickup")]
    Pickup,
    #[serde(rename = "delivery")]
    Delivery,
    #[serde(rename = "break")]
    Break,
    #[serde(rename = "end")]
    End,
}

impl Default for Type {
    fn default() -> Type {
        Self::Start
    }
}

