/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptimizationPost200ResponseSummaryViolationsInner : Note on violations: reporting only really makes sense when using -c to choose ETA for custom routes described in input using the steps keys for a vehicle. When using regular optimization, violations are still reported for consistency, but are guaranteed to be \"void\", i.e. violations arrays are empty. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPost200ResponseSummaryViolationsInner {
    /// string describing the cause of violation. Possible violation causes are:             - \"delay\" if actual service start does not meet a task time window and is late on a time window end             - \"lead_time\" if actual service start does not meet a task time window and is early on a time window start             - \"load\" if the vehicle load goes over its capacity             - \"max_tasks\" if the vehicle has more tasks than its max_tasks value             - \"skills\" if the vehicle does not hold all required skills for a task             - \"precedence\" if a shipment precedence constraint is not met (pickup without matching delivery, delivery before/without matching pickup)             - \"missing_break\" if a vehicle break has been omitted in its custom route             - \"max_travel_time\" if the vehicle has more travel time than its max_travel_time value             - \"max_load\" if the load during a break exceed its max_load value 
    #[serde(rename = "cause", skip_serializing_if = "Option::is_none")]
    pub cause: Option<String>,
    /// Earliness (resp. lateness) if `cause` is \"lead_time\" (resp \"delay\") 
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
}

impl OptimizationPost200ResponseSummaryViolationsInner {
    /// Note on violations: reporting only really makes sense when using -c to choose ETA for custom routes described in input using the steps keys for a vehicle. When using regular optimization, violations are still reported for consistency, but are guaranteed to be \"void\", i.e. violations arrays are empty. 
    pub fn new() -> OptimizationPost200ResponseSummaryViolationsInner {
        OptimizationPost200ResponseSummaryViolationsInner {
            cause: None,
            duration: None,
        }
    }
}

