/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptimizationPost200ResponseUnassignedInner : Unassigned Job with `id` and `location` (if provided)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPost200ResponseUnassignedInner {
    /// The `id` of the unassigned job\"
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The `location` of the unassigned job
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<f32>>,
}

impl OptimizationPost200ResponseUnassignedInner {
    /// Unassigned Job with `id` and `location` (if provided)
    pub fn new() -> OptimizationPost200ResponseUnassignedInner {
        OptimizationPost200ResponseUnassignedInner {
            id: None,
            location: None,
        }
    }
}

