/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptimizationPostRequestOptions : Additional options passed to the optimization engine.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPostRequestOptions {
    /// Calculate geometries for the optimized routes.
    #[serde(rename = "g", skip_serializing_if = "Option::is_none")]
    pub g: Option<bool>,
}

impl OptimizationPostRequestOptions {
    /// Additional options passed to the optimization engine.
    pub fn new() -> OptimizationPostRequestOptions {
        OptimizationPostRequestOptions {
            g: None,
        }
    }
}

