/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptimizationPost200ResponseSummary : object summarizing solution indicators 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPost200ResponseSummary {
    /// total cost for all routes
    #[serde(rename = "cost", skip_serializing_if = "Option::is_none")]
    pub cost: Option<f64>,
    /// Number of routes in the solution 
    #[serde(rename = "routes", skip_serializing_if = "Option::is_none")]
    pub routes: Option<f64>,
    /// number of jobs that could not be served
    #[serde(rename = "unassigned", skip_serializing_if = "Option::is_none")]
    pub unassigned: Option<i32>,
    /// Total setup time for all routes 
    #[serde(rename = "setup", skip_serializing_if = "Option::is_none")]
    pub setup: Option<f64>,
    /// total service time for all routes
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<f32>,
    /// total travel time for all routes
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f32>,
    /// total waiting time for all routes
    #[serde(rename = "waiting_time", skip_serializing_if = "Option::is_none")]
    pub waiting_time: Option<f32>,
    /// total priority sum for all assigned tasks
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<f64>,
    /// array of violation objects for all routes
    #[serde(rename = "violations", skip_serializing_if = "Option::is_none")]
    pub violations: Option<Vec<models::OptimizationPost200ResponseSummaryViolationsInner>>,
    /// Total delivery for all routes
    #[serde(rename = "delivery", skip_serializing_if = "Option::is_none")]
    pub delivery: Option<f64>,
    /// Total pickup for all routes
    #[serde(rename = "pickup", skip_serializing_if = "Option::is_none")]
    pub pickup: Option<f64>,
    /// total distance for all routes. Only provided when using the `-g` flag with `OSRM`
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f32>,
}

impl OptimizationPost200ResponseSummary {
    /// object summarizing solution indicators 
    pub fn new() -> OptimizationPost200ResponseSummary {
        OptimizationPost200ResponseSummary {
            cost: None,
            routes: None,
            unassigned: None,
            setup: None,
            service: None,
            duration: None,
            waiting_time: None,
            priority: None,
            violations: None,
            delivery: None,
            pickup: None,
            distance: None,
        }
    }
}

