/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPostRequestVehiclesInnerCosts {
    /// integer defining the cost of using this vehicle in the solution (defaults to 0) 
    #[serde(rename = "fixed", skip_serializing_if = "Option::is_none")]
    pub fixed: Option<f64>,
    /// integer defining the cost for one hour of travel time with this vehicle (defaults to 3600) 
    #[serde(rename = "per_hour", skip_serializing_if = "Option::is_none")]
    pub per_hour: Option<f64>,
    /// integer defining the cost for one km of travel time with this vehicle (defaults to 0) 
    #[serde(rename = "per_km", skip_serializing_if = "Option::is_none")]
    pub per_km: Option<f64>,
}

impl OptimizationPostRequestVehiclesInnerCosts {
    pub fn new() -> OptimizationPostRequestVehiclesInnerCosts {
        OptimizationPostRequestVehiclesInnerCosts {
            fixed: None,
            per_hour: None,
            per_km: None,
        }
    }
}

