/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPost200ResponseRoutesInner {
    /// id of the vehicle assigned to this route
    #[serde(rename = "vehicle", skip_serializing_if = "Option::is_none")]
    pub vehicle: Option<i32>,
    /// array of `step` objects
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<models::OptimizationPost200ResponseRoutesInnerStepsInner>>,
    /// cost for this route
    #[serde(rename = "cost", skip_serializing_if = "Option::is_none")]
    pub cost: Option<f32>,
    /// total service time for this route
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<f32>,
    /// total travel time for this route
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f32>,
    /// total waiting time for this route
    #[serde(rename = "waiting_time", skip_serializing_if = "Option::is_none")]
    pub waiting_time: Option<f32>,
    /// Total delivery for tasks in this route
    #[serde(rename = "delivery", skip_serializing_if = "Option::is_none")]
    pub delivery: Option<Vec<i32>>,
    /// total pickup for tasks in this route
    #[serde(rename = "pickup", skip_serializing_if = "Option::is_none")]
    pub pickup: Option<Vec<i32>>,
    /// vehicle description, if provided in input 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// polyline encoded route geometry. Only provided when using the `-g` flag
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<String>,
    /// total route distance. Only provided when using the `-g` flag
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f32>,
}

impl OptimizationPost200ResponseRoutesInner {
    pub fn new() -> OptimizationPost200ResponseRoutesInner {
        OptimizationPost200ResponseRoutesInner {
            vehicle: None,
            steps: None,
            cost: None,
            service: None,
            duration: None,
            waiting_time: None,
            delivery: None,
            pickup: None,
            description: None,
            geometry: None,
            distance: None,
        }
    }
}

