/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptimizationPostRequestMatrices : The matrices object allows to input (non-empty) custom matrices for each vehicle profile.  If only the durations matrix is provided, internal costs are derived from durations based on vehicles costs properties.  If custom matrices are provided for all required vehicle profile values, the location, start and end properties become optional. Instead of the coordinates, row and column indications provided with the *_index keys are used during optimization. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPostRequestMatrices {
    #[serde(rename = "driving-car", skip_serializing_if = "Option::is_none")]
    pub driving_car: Option<Box<models::OptimizationPostRequestMatricesDrivingCar>>,
    #[serde(rename = "driving-hgv", skip_serializing_if = "Option::is_none")]
    pub driving_hgv: Option<Box<models::OptimizationPostRequestMatricesDrivingCar>>,
    #[serde(rename = "cycling-regular", skip_serializing_if = "Option::is_none")]
    pub cycling_regular: Option<Box<models::OptimizationPostRequestMatricesDrivingCar>>,
    #[serde(rename = "cycling-mountain", skip_serializing_if = "Option::is_none")]
    pub cycling_mountain: Option<Box<models::OptimizationPostRequestMatricesDrivingCar>>,
    #[serde(rename = "cycling-electric", skip_serializing_if = "Option::is_none")]
    pub cycling_electric: Option<Box<models::OptimizationPostRequestMatricesDrivingCar>>,
    #[serde(rename = "cycling-road", skip_serializing_if = "Option::is_none")]
    pub cycling_road: Option<Box<models::OptimizationPostRequestMatricesDrivingCar>>,
    #[serde(rename = "foot-walking", skip_serializing_if = "Option::is_none")]
    pub foot_walking: Option<Box<models::OptimizationPostRequestMatricesDrivingCar>>,
    #[serde(rename = "foot-hiking", skip_serializing_if = "Option::is_none")]
    pub foot_hiking: Option<Box<models::OptimizationPostRequestMatricesDrivingCar>>,
    #[serde(rename = "wheelchair", skip_serializing_if = "Option::is_none")]
    pub wheelchair: Option<Box<models::OptimizationPostRequestMatricesDrivingCar>>,
}

impl OptimizationPostRequestMatrices {
    /// The matrices object allows to input (non-empty) custom matrices for each vehicle profile.  If only the durations matrix is provided, internal costs are derived from durations based on vehicles costs properties.  If custom matrices are provided for all required vehicle profile values, the location, start and end properties become optional. Instead of the coordinates, row and column indications provided with the *_index keys are used during optimization. 
    pub fn new() -> OptimizationPostRequestMatrices {
        OptimizationPostRequestMatrices {
            driving_car: None,
            driving_hgv: None,
            cycling_regular: None,
            cycling_mountain: None,
            cycling_electric: None,
            cycling_road: None,
            foot_walking: None,
            foot_hiking: None,
            wheelchair: None,
        }
    }
}

