/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptimizationPostRequestMatricesDrivingCar : Contains `durations`, `distances` or `cost` matrices for a profile
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPostRequestMatricesDrivingCar {
    /// Durations for a custom travel-time matrix that will be used for all checks against timing constraints
    #[serde(rename = "durations", skip_serializing_if = "Option::is_none")]
    pub durations: Option<Vec<Vec<i32>>>,
    /// distances for a custom distance matrix
    #[serde(rename = "distances", skip_serializing_if = "Option::is_none")]
    pub distances: Option<Vec<Vec<i32>>>,
    /// costs for a custom cost matrix that will be used within all route cost evaluations
    #[serde(rename = "costs", skip_serializing_if = "Option::is_none")]
    pub costs: Option<Vec<Vec<i32>>>,
}

impl OptimizationPostRequestMatricesDrivingCar {
    /// Contains `durations`, `distances` or `cost` matrices for a profile
    pub fn new() -> OptimizationPostRequestMatricesDrivingCar {
        OptimizationPostRequestMatricesDrivingCar {
            durations: None,
            distances: None,
            costs: None,
        }
    }
}

