/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptimizationPostRequestJobsInner : If a custom matrix is provided: - `location_index` is mandatory - `location` is optional but can be set to retrieve coordinates in the response  If no custom matrix is provided: - a `matrix` query will be sent to ORS - `location` is mandatory - `location_index` is irrelevant 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPostRequestJobsInner {
    /// an integer used as unique identifier 
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// a string describing this job 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// coordinates array in `[lon, lat]` 
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<Vec<f32>>>,
    /// index of relevant row and column in custom matrix 
    #[serde(rename = "location_index", skip_serializing_if = "Option::is_none")]
    pub location_index: Option<serde_json::Value>,
    /// job setup duration (defaults to 0), in seconds 
    #[serde(rename = "setup", skip_serializing_if = "Option::is_none")]
    pub setup: Option<f64>,
    /// job service duration (defaults to 0), in seconds 
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<serde_json::Value>,
    /// an array of integers describing multidimensional quantities for delivery 
    #[serde(rename = "delivery", skip_serializing_if = "Option::is_none")]
    pub delivery: Option<Vec<f64>>,
    /// an array of integers describing multidimensional quantities for pickup 
    #[serde(rename = "pickup", skip_serializing_if = "Option::is_none")]
    pub pickup: Option<Vec<f64>>,
    /// Array of integers defining mandatory skills for this job 
    #[serde(rename = "skills", skip_serializing_if = "Option::is_none")]
    pub skills: Option<Vec<i32>>,
    /// an integer in the range [0, 100] describing priority level (defaults to 0) 
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<f64>,
    /// Array of `time_window` arrays describing valid slots for job service start and end, in week seconds, i.e. 28800 = Mon, 8 AM. 
    #[serde(rename = "time_windows", skip_serializing_if = "Option::is_none")]
    pub time_windows: Option<Vec<Vec<i32>>>,
}

impl OptimizationPostRequestJobsInner {
    /// If a custom matrix is provided: - `location_index` is mandatory - `location` is optional but can be set to retrieve coordinates in the response  If no custom matrix is provided: - a `matrix` query will be sent to ORS - `location` is mandatory - `location_index` is irrelevant 
    pub fn new() -> OptimizationPostRequestJobsInner {
        OptimizationPostRequestJobsInner {
            id: None,
            description: None,
            location: None,
            location_index: None,
            setup: None,
            service: None,
            delivery: None,
            pickup: None,
            skills: None,
            priority: None,
            time_windows: None,
        }
    }
}

