/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPost200Response {
    /// status code. Possible values:   Value         | Status |  :-----------: | :-----------: |  `0` | no error raised |  `1` | internal error |  `2` | input error |  `3` | routing error | 
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// error message (present if `code` is different from `0`) 
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<models::OptimizationPost200ResponseSummary>>,
    /// array of objects describing unassigned jobs with their `id` and `location` (if provided) 
    #[serde(rename = "unassigned", skip_serializing_if = "Option::is_none")]
    pub unassigned: Option<Vec<models::OptimizationPost200ResponseUnassignedInner>>,
    /// array of `route` objects 
    #[serde(rename = "routes", skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<models::OptimizationPost200ResponseRoutesInner>>,
}

impl OptimizationPost200Response {
    pub fn new() -> OptimizationPost200Response {
        OptimizationPost200Response {
            code: None,
            error: None,
            summary: None,
            unassigned: None,
            routes: None,
        }
    }
}

