/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptimizationPostRequestVehiclesInner : A vehicle object with capacity, time windows and skills. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPostRequestVehiclesInner {
    /// Integer used as unique identifier 
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The ORS routing profile for the vehicle. 
    #[serde(rename = "profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<Profile>,
    /// a string describing this vehicle 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Start coordinates array in `[lon, lat]` format. If left blank, the optimization engine will identify the optimal start point. 
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<Vec<f32>>,
    /// Index of relevant row and column in custom matrix. 
    #[serde(rename = "start_index", skip_serializing_if = "Option::is_none")]
    pub start_index: Option<serde_json::Value>,
    /// End coordinates array in `[lon, lat]` format. If left blank, the optimization engine will identify the optimal end point. 
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<Vec<f32>>,
    /// Index of relevant row and column in custom matrix. 
    #[serde(rename = "end_index", skip_serializing_if = "Option::is_none")]
    pub end_index: Option<serde_json::Value>,
    /// Array of integers describing multidimensional quantities. 
    #[serde(rename = "capacity", skip_serializing_if = "Option::is_none")]
    pub capacity: Option<Vec<i32>>,
    #[serde(rename = "costs", skip_serializing_if = "Option::is_none")]
    pub costs: Option<Box<models::OptimizationPostRequestVehiclesInnerCosts>>,
    /// Array of integers defining skills for this vehicle 
    #[serde(rename = "skills", skip_serializing_if = "Option::is_none")]
    pub skills: Option<Vec<i32>>,
    /// A `time_window` array describing working hours for this vehicle, in week seconds, i.e. 28800 = Mon, 8 AM. 
    #[serde(rename = "time_window", skip_serializing_if = "Option::is_none")]
    pub time_window: Option<Vec<i32>>,
    /// An array of `break` objects 
    #[serde(rename = "breaks", skip_serializing_if = "Option::is_none")]
    pub breaks: Option<Vec<models::OptimizationPostRequestVehiclesInnerBreaksInner>>,
    /// A double value in the range (0, 5] used to scale all vehicle travel times (defaults to 1.). The respected precision is limited to two digits after the decimal point. 
    #[serde(rename = "speed_factor", skip_serializing_if = "Option::is_none")]
    pub speed_factor: Option<f32>,
    /// an integer defining the maximum number of tasks in a route for this vehicle 
    #[serde(rename = "max_tasks", skip_serializing_if = "Option::is_none")]
    pub max_tasks: Option<f64>,
    /// an integer defining the maximum travel time for this vehicle 
    #[serde(rename = "max_travel_time", skip_serializing_if = "Option::is_none")]
    pub max_travel_time: Option<f64>,
    /// an integer defining the maximum distance for this vehicle 
    #[serde(rename = "max_distance", skip_serializing_if = "Option::is_none")]
    pub max_distance: Option<f64>,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<models::OptimizationPostRequestVehiclesInnerStepsInner>>,
}

impl OptimizationPostRequestVehiclesInner {
    /// A vehicle object with capacity, time windows and skills. 
    pub fn new() -> OptimizationPostRequestVehiclesInner {
        OptimizationPostRequestVehiclesInner {
            id: None,
            profile: None,
            description: None,
            start: None,
            start_index: None,
            end: None,
            end_index: None,
            capacity: None,
            costs: None,
            skills: None,
            time_window: None,
            breaks: None,
            speed_factor: None,
            max_tasks: None,
            max_travel_time: None,
            max_distance: None,
            steps: None,
        }
    }
}
/// The ORS routing profile for the vehicle. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Profile {
    #[serde(rename = "driving-car")]
    DrivingCar,
    #[serde(rename = "driving-hgv")]
    DrivingHgv,
    #[serde(rename = "cycling-regular")]
    CyclingRegular,
    #[serde(rename = "cycling-mountain")]
    CyclingMountain,
    #[serde(rename = "cycling-electric")]
    CyclingElectric,
    #[serde(rename = "cycling-road")]
    CyclingRoad,
    #[serde(rename = "foot-walking")]
    FootWalking,
    #[serde(rename = "foot-hiking")]
    FootHiking,
    #[serde(rename = "wheelchair")]
    Wheelchair,
}

impl Default for Profile {
    fn default() -> Profile {
        Self::DrivingCar
    }
}

