/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptimizationPostRequestVehiclesInnerBreaksInner {
    /// Integer used as unique identifier 
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Array of time_window objects describing valid slots for break start and end, in week seconds, i.e. 28800 = Mon, 8 AM. 
    #[serde(rename = "time_windows", skip_serializing_if = "Option::is_none")]
    pub time_windows: Option<Vec<Vec<i32>>>,
    /// break duration in seconds (defaults to 0) 
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<f64>,
    /// a string describing this break 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Array of integers describing the maximum vehicle load for which this break can happen. An error is reported if two break objects have the same id for the same vehicle. 
    #[serde(rename = "max_load", skip_serializing_if = "Option::is_none")]
    pub max_load: Option<Vec<f64>>,
}

impl OptimizationPostRequestVehiclesInnerBreaksInner {
    pub fn new() -> OptimizationPostRequestVehiclesInnerBreaksInner {
        OptimizationPostRequestVehiclesInnerBreaksInner {
            id: None,
            time_windows: None,
            service: None,
            description: None,
            max_load: None,
        }
    }
}

