/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlternativeRoutes : Specifies whether alternative routes are computed, and parameters for the algorithm determining suitable alternatives.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlternativeRoutes {
    /// Target number of alternative routes to compute. Service returns up to this number of routes that fulfill the share-factor and weight-factor constraints.
    #[serde(rename = "target_count", skip_serializing_if = "Option::is_none")]
    pub target_count: Option<i32>,
    /// Maximum factor by which route weight may diverge from the optimal route. The default value of 1.4 means alternatives can be up to 1.4 times longer (costly) than the optimal route.
    #[serde(rename = "weight_factor", skip_serializing_if = "Option::is_none")]
    pub weight_factor: Option<f64>,
    /// Maximum fraction of the route that alternatives may share with the optimal route. The default value of 0.6 means alternatives can share up to 60% of path segments with the optimal route.
    #[serde(rename = "share_factor", skip_serializing_if = "Option::is_none")]
    pub share_factor: Option<f64>,
}

impl AlternativeRoutes {
    /// Specifies whether alternative routes are computed, and parameters for the algorithm determining suitable alternatives.
    pub fn new() -> AlternativeRoutes {
        AlternativeRoutes {
            target_count: None,
            weight_factor: None,
            share_factor: None,
        }
    }
}

