/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DirectionsServiceCustomModelSpeedInner : Array of objects describing rules to be applied to the priority of edges
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectionsServiceCustomModelSpeedInner {
    #[serde(rename = "keyword", skip_serializing_if = "Option::is_none")]
    pub keyword: Option<Keyword>,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<Operation>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
}

impl DirectionsServiceCustomModelSpeedInner {
    /// Array of objects describing rules to be applied to the priority of edges
    pub fn new() -> DirectionsServiceCustomModelSpeedInner {
        DirectionsServiceCustomModelSpeedInner {
            keyword: None,
            condition: None,
            operation: None,
            value: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Keyword {
    #[serde(rename = "IF")]
    If,
    #[serde(rename = "ELSEIF")]
    Elseif,
    #[serde(rename = "ELSE")]
    Else,
}

impl Default for Keyword {
    fn default() -> Keyword {
        Self::If
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operation {
    #[serde(rename = "MULTIPLY")]
    Multiply,
    #[serde(rename = "LIMIT")]
    Limit,
}

impl Default for Operation {
    fn default() -> Operation {
        Self::Multiply
    }
}

