/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DirectionsService : The JSON body request sent to the routing service which defines options and parameters regarding the route to generate.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectionsService {
    /// The waypoints to use for the route as an array of `longitude/latitude` pairs in WGS 84 (EPSG:4326)
    #[serde(rename = "coordinates")]
    pub coordinates: Vec<Vec<f64>>,
    /// Arbitrary identification string of the request reflected in the meta information.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Specifies the route preference
    #[serde(rename = "preference", skip_serializing_if = "Option::is_none")]
    pub preference: Option<Preference>,
    /// Specifies the distance unit.
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<Units>,
    /// Language for the route instructions.
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<Language>,
    /// Specifies whether to return geometry. 
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<bool>,
    /// Specifies whether to return instructions.
    #[serde(rename = "instructions", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<bool>,
    /// Select html for more verbose instructions.
    #[serde(rename = "instructions_format", skip_serializing_if = "Option::is_none")]
    pub instructions_format: Option<InstructionsFormat>,
    /// Provides bearings of the entrance and all passed roundabout exits. Adds the `exit_bearings` array to the step object in the response. 
    #[serde(rename = "roundabout_exits", skip_serializing_if = "Option::is_none")]
    pub roundabout_exits: Option<bool>,
    /// List of route attributes
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<Attributes>>,
    /// Specifies whether the maneuver object is included into the step object or not. 
    #[serde(rename = "maneuvers", skip_serializing_if = "Option::is_none")]
    pub maneuvers: Option<bool>,
    /// A list of maximum distances (measured in metres) that limit the search of nearby road segments to every given waypoint. The values must be greater than 0, the value of -1 specifies using the maximum possible search radius. The number of radiuses correspond to the number of waypoints. If only a single value is given, it will be applied to all waypoints.
    #[serde(rename = "radiuses", skip_serializing_if = "Option::is_none")]
    pub radiuses: Option<Vec<f64>>,
    /// Specifies a list of pairs (bearings and deviations) to filter the segments of the road network a waypoint can snap to. \"For example `bearings=[[45,10],[120,20]]`. \"Each pair is a comma-separated list that can consist of one or two float values, where the first value is the bearing and the second one is the allowed deviation from the bearing. \"The bearing can take values between `0` and `360` clockwise from true north. If the deviation is not set, then the default value of `100` degrees is used. \"The number of pairs must correspond to the number of waypoints. \"The number of bearings corresponds to the length of waypoints-1 or waypoints. If the bearing information for the last waypoint is given, then this will control the sector from which the destination waypoint may be reached. \"You can skip a bearing for a certain waypoint by passing an empty value for an array, e.g. `[30,20],[],[40,20]`.
    #[serde(rename = "bearings", skip_serializing_if = "Option::is_none")]
    pub bearings: Option<Vec<Vec<f64>>>,
    /// Forces the route to keep going straight at waypoints restricting uturns there even if it would be faster.
    #[serde(rename = "continue_straight", skip_serializing_if = "Option::is_none")]
    pub continue_straight: Option<bool>,
    /// Specifies whether to return elevation values for points. Please note that elevation also gets encoded for json response encoded polyline.
    #[serde(rename = "elevation", skip_serializing_if = "Option::is_none")]
    pub elevation: Option<bool>,
    /// The extra info items to include in the response
    #[serde(rename = "extra_info", skip_serializing_if = "Option::is_none")]
    pub extra_info: Option<Vec<ExtraInfo>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::RouteOptions>>,
    /// Suppress warning messages in the response
    #[serde(rename = "suppress_warnings", skip_serializing_if = "Option::is_none")]
    pub suppress_warnings: Option<bool>,
    /// Specifies whether to simplify the geometry. Simplify geometry cannot be applied to routes with more than **one segment** and when `extra_info` is required.
    #[serde(rename = "geometry_simplify", skip_serializing_if = "Option::is_none")]
    pub geometry_simplify: Option<bool>,
    /// Specifies the segments that should be skipped in the route calculation. A segment is the connection between two given coordinates and the counting starts with 1 for the connection between the first and second coordinate.
    #[serde(rename = "skip_segments", skip_serializing_if = "Option::is_none")]
    pub skip_segments: Option<Vec<i32>>,
    #[serde(rename = "alternative_routes", skip_serializing_if = "Option::is_none")]
    pub alternative_routes: Option<Box<models::AlternativeRoutes>>,
    /// The maximum speed specified by user.
    #[serde(rename = "maximum_speed", skip_serializing_if = "Option::is_none")]
    pub maximum_speed: Option<f64>,
    /// If true, return a public transport schedule starting at <departure> for the next <schedule_duration> minutes.
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<bool>,
    #[serde(rename = "schedule_duration", skip_serializing_if = "Option::is_none")]
    pub schedule_duration: Option<String>,
    /// The maximum amount of entries that should be returned when requesting a schedule.
    #[serde(rename = "schedule_rows", skip_serializing_if = "Option::is_none")]
    pub schedule_rows: Option<i32>,
    #[serde(rename = "walking_time", skip_serializing_if = "Option::is_none")]
    pub walking_time: Option<String>,
    /// Specifies if transfers as criterion should be ignored.
    #[serde(rename = "ignore_transfers", skip_serializing_if = "Option::is_none")]
    pub ignore_transfers: Option<bool>,
    #[serde(rename = "custom_model", skip_serializing_if = "Option::is_none")]
    pub custom_model: Option<Box<models::DirectionsServiceCustomModel>>,
}

impl DirectionsService {
    /// The JSON body request sent to the routing service which defines options and parameters regarding the route to generate.
    pub fn new(coordinates: Vec<Vec<f64>>) -> DirectionsService {
        DirectionsService {
            coordinates,
            id: None,
            preference: None,
            units: None,
            language: None,
            geometry: None,
            instructions: None,
            instructions_format: None,
            roundabout_exits: None,
            attributes: None,
            maneuvers: None,
            radiuses: None,
            bearings: None,
            continue_straight: None,
            elevation: None,
            extra_info: None,
            options: None,
            suppress_warnings: None,
            geometry_simplify: None,
            skip_segments: None,
            alternative_routes: None,
            maximum_speed: None,
            schedule: None,
            schedule_duration: None,
            schedule_rows: None,
            walking_time: None,
            ignore_transfers: None,
            custom_model: None,
        }
    }
}
/// Specifies the route preference
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Preference {
    #[serde(rename = "fastest")]
    Fastest,
    #[serde(rename = "shortest")]
    Shortest,
    #[serde(rename = "recommended")]
    Recommended,
    #[serde(rename = "custom")]
    Custom,
}

impl Default for Preference {
    fn default() -> Preference {
        Self::Fastest
    }
}
/// Specifies the distance unit.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Units {
    #[serde(rename = "m")]
    M,
    #[serde(rename = "km")]
    Km,
    #[serde(rename = "mi")]
    Mi,
}

impl Default for Units {
    fn default() -> Units {
        Self::M
    }
}
/// Language for the route instructions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Language {
    #[serde(rename = "cs")]
    Cs,
    #[serde(rename = "cs-cz")]
    CsCz,
    #[serde(rename = "da")]
    Da,
    #[serde(rename = "dk-da")]
    DkDa,
    #[serde(rename = "de")]
    De,
    #[serde(rename = "de-de")]
    DeDe,
    #[serde(rename = "en")]
    En,
    #[serde(rename = "en-us")]
    EnUs,
    #[serde(rename = "eo")]
    Eo,
    #[serde(rename = "eo-eo")]
    EoEo,
    #[serde(rename = "es")]
    Es,
    #[serde(rename = "es-es")]
    EsEs,
    #[serde(rename = "fi")]
    Fi,
    #[serde(rename = "fi-fi")]
    FiFi,
    #[serde(rename = "fr")]
    Fr,
    #[serde(rename = "fr-fr")]
    FrFr,
    #[serde(rename = "gr")]
    Gr,
    #[serde(rename = "gr-gr")]
    GrGr,
    #[serde(rename = "he")]
    He,
    #[serde(rename = "he-il")]
    HeIl,
    #[serde(rename = "hu")]
    Hu,
    #[serde(rename = "hu-hu")]
    HuHu,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "id-id")]
    IdId,
    #[serde(rename = "it")]
    It,
    #[serde(rename = "it-it")]
    ItIt,
    #[serde(rename = "ja")]
    Ja,
    #[serde(rename = "ja-jp")]
    JaJp,
    #[serde(rename = "lv")]
    Lv,
    #[serde(rename = "lv-lv")]
    LvLv,
    #[serde(rename = "lt")]
    Lt,
    #[serde(rename = "lt-lt")]
    LtLt,
    #[serde(rename = "ne")]
    Ne,
    #[serde(rename = "ne-np")]
    NeNp,
    #[serde(rename = "nl")]
    Nl,
    #[serde(rename = "nl-nl")]
    NlNl,
    #[serde(rename = "nb")]
    Nb,
    #[serde(rename = "nb-no")]
    NbNo,
    #[serde(rename = "pl")]
    Pl,
    #[serde(rename = "pl-pl")]
    PlPl,
    #[serde(rename = "pt")]
    Pt,
    #[serde(rename = "pt-pt")]
    PtPt,
    #[serde(rename = "ro")]
    Ro,
    #[serde(rename = "ro-ro")]
    RoRo,
    #[serde(rename = "ru")]
    Ru,
    #[serde(rename = "ru-ru")]
    RuRu,
    #[serde(rename = "tr")]
    Tr,
    #[serde(rename = "tr-tr")]
    TrTr,
    #[serde(rename = "ua")]
    Ua,
    #[serde(rename = "ua-ua")]
    UaUa,
    #[serde(rename = "vi")]
    Vi,
    #[serde(rename = "vi-vn")]
    ViVn,
    #[serde(rename = "zh")]
    Zh,
    #[serde(rename = "zh-cn")]
    ZhCn,
}

impl Default for Language {
    fn default() -> Language {
        Self::Cs
    }
}
/// Select html for more verbose instructions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstructionsFormat {
    #[serde(rename = "html")]
    Html,
    #[serde(rename = "text")]
    Text,
}

impl Default for InstructionsFormat {
    fn default() -> InstructionsFormat {
        Self::Html
    }
}
/// List of route attributes
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Attributes {
    #[serde(rename = "avgspeed")]
    Avgspeed,
    #[serde(rename = "detourfactor")]
    Detourfactor,
    #[serde(rename = "percentage")]
    Percentage,
}

impl Default for Attributes {
    fn default() -> Attributes {
        Self::Avgspeed
    }
}
/// The extra info items to include in the response
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExtraInfo {
    #[serde(rename = "steepness")]
    Steepness,
    #[serde(rename = "suitability")]
    Suitability,
    #[serde(rename = "surface")]
    Surface,
    #[serde(rename = "waycategory")]
    Waycategory,
    #[serde(rename = "waytype")]
    Waytype,
    #[serde(rename = "tollways")]
    Tollways,
    #[serde(rename = "traildifficulty")]
    Traildifficulty,
    #[serde(rename = "osmid")]
    Osmid,
    #[serde(rename = "roadaccessrestrictions")]
    Roadaccessrestrictions,
    #[serde(rename = "countryinfo")]
    Countryinfo,
    #[serde(rename = "green")]
    Green,
    #[serde(rename = "noise")]
    Noise,
    #[serde(rename = "csv")]
    Csv,
    #[serde(rename = "shadow")]
    Shadow,
}

impl Default for ExtraInfo {
    fn default() -> ExtraInfo {
        Self::Steepness
    }
}

