/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EngineInfo : Information about the openrouteservice engine used
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EngineInfo {
    /// The backend version of the openrouteservice that was queried
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// The date that the service was last updated
    #[serde(rename = "build_date", skip_serializing_if = "Option::is_none")]
    pub build_date: Option<String>,
    /// The date that the graph data was last updated
    #[serde(rename = "graph_date", skip_serializing_if = "Option::is_none")]
    pub graph_date: Option<String>,
    /// Timestamp of the OSM data the graph was built from
    #[serde(rename = "osm_date", skip_serializing_if = "Option::is_none")]
    pub osm_date: Option<String>,
}

impl EngineInfo {
    /// Information about the openrouteservice engine used
    pub fn new() -> EngineInfo {
        EngineInfo {
            version: None,
            build_date: None,
            graph_date: None,
            osm_date: None,
        }
    }
}

