/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GeoJsonSnappingResponse : The GeoJSON Snapping Response contains the snapped coordinates in GeoJSON format.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoJsonSnappingResponse {
    /// GeoJSON type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Information about the service and request
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<models::GetGeoJsonSnapping200ResponseFeaturesInner>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::GetDefault200ResponseMetadata>>,
    /// Bounding box that covers all returned snapping points
    #[serde(rename = "bbox", skip_serializing_if = "Option::is_none")]
    pub bbox: Option<Vec<f64>>,
}

impl GeoJsonSnappingResponse {
    /// The GeoJSON Snapping Response contains the snapped coordinates in GeoJSON format.
    pub fn new() -> GeoJsonSnappingResponse {
        GeoJsonSnappingResponse {
            r#type: None,
            features: None,
            metadata: None,
            bbox: None,
        }
    }
}

