/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GeoJsonFeature : Information about the service and request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoJsonFeature {
    /// GeoJSON type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::GetGeoJsonSnapping200ResponseFeaturesInnerProperties>>,
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<Box<models::GetGeoJsonSnapping200ResponseFeaturesInnerGeometry>>,
}

impl GeoJsonFeature {
    /// Information about the service and request
    pub fn new() -> GeoJsonFeature {
        GeoJsonFeature {
            r#type: None,
            properties: None,
            geometry: None,
        }
    }
}

