/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefault2200Response : The Export Response contains nodes and edge weights from the requested BBox
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault2200Response {
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<Vec<models::GetDefault2200ResponseNodesInner>>,
    #[serde(rename = "edges", skip_serializing_if = "Option::is_none")]
    pub edges: Option<Vec<models::GetDefault2200ResponseEdgesInner>>,
    #[serde(rename = "edges_extra", skip_serializing_if = "Option::is_none")]
    pub edges_extra: Option<Vec<models::GetDefault2200ResponseEdgesExtraInner>>,
    #[serde(rename = "warning", skip_serializing_if = "Option::is_none")]
    pub warning: Option<Box<models::GetDefault2200ResponseWarning>>,
    #[serde(rename = "nodes_count", skip_serializing_if = "Option::is_none")]
    pub nodes_count: Option<i64>,
    #[serde(rename = "edges_count", skip_serializing_if = "Option::is_none")]
    pub edges_count: Option<i64>,
}

impl GetDefault2200Response {
    /// The Export Response contains nodes and edge weights from the requested BBox
    pub fn new() -> GetDefault2200Response {
        GetDefault2200Response {
            nodes: None,
            edges: None,
            edges_extra: None,
            warning: None,
            nodes_count: None,
            edges_count: None,
        }
    }
}

