/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefault2200ResponseWarning : Informs about possible difficulties like access restrictions on the generated route. Generates a corresponding `extras` object with the affected segments.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault2200ResponseWarning {
    /// Identification code for the warning
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// The message associated with the warning
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl GetDefault2200ResponseWarning {
    /// Informs about possible difficulties like access restrictions on the generated route. Generates a corresponding `extras` object with the affected segments.
    pub fn new() -> GetDefault2200ResponseWarning {
        GetDefault2200ResponseWarning {
            code: None,
            message: None,
        }
    }
}

