/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefault3200ResponseRoutesInner : An individual JSON based route created by the service
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault3200ResponseRoutesInner {
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<models::GetDefault3200ResponseRoutesInnerSummary>>,
    /// List containing the segments and its corresponding steps which make up the route.
    #[serde(rename = "segments", skip_serializing_if = "Option::is_none")]
    pub segments: Option<Vec<models::GetDefault3200ResponseRoutesInnerSegmentsInner>>,
    /// A bounding box which contains the entire route
    #[serde(rename = "bbox", skip_serializing_if = "Option::is_none")]
    pub bbox: Option<Vec<f64>>,
    /// The geometry of the route. For JSON route responses this is an encoded polyline.
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<String>,
    /// List containing the indices of way points corresponding to the *geometry*.
    #[serde(rename = "way_points", skip_serializing_if = "Option::is_none")]
    pub way_points: Option<Vec<i32>>,
    /// List of warnings that have been generated for the route
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<models::GetDefault2200ResponseWarning>>,
    /// List containing the legs the route consists of.
    #[serde(rename = "legs", skip_serializing_if = "Option::is_none")]
    pub legs: Option<Vec<models::GetDefault3200ResponseRoutesInnerLegsInner>>,
    /// List of extra info objects representing the extra info items that were requested for the route.
    #[serde(rename = "extras", skip_serializing_if = "Option::is_none")]
    pub extras: Option<std::collections::HashMap<String, models::GetDefault3200ResponseRoutesInnerExtrasValue>>,
    /// Departure date and time
    #[serde(rename = "departure", skip_serializing_if = "Option::is_none")]
    pub departure: Option<String>,
    /// Arrival date and time
    #[serde(rename = "arrival", skip_serializing_if = "Option::is_none")]
    pub arrival: Option<String>,
}

impl GetDefault3200ResponseRoutesInner {
    /// An individual JSON based route created by the service
    pub fn new() -> GetDefault3200ResponseRoutesInner {
        GetDefault3200ResponseRoutesInner {
            summary: None,
            segments: None,
            bbox: None,
            geometry: None,
            way_points: None,
            warnings: None,
            legs: None,
            extras: None,
            departure: None,
            arrival: None,
        }
    }
}

