/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault2200ResponseEdgesExtraInner {
    /// Id of the corresponding edge in the graph
    #[serde(rename = "edgeId", skip_serializing_if = "Option::is_none")]
    pub edge_id: Option<String>,
    /// Extra info stored on the edge
    #[serde(rename = "extra", skip_serializing_if = "Option::is_none")]
    pub extra: Option<serde_json::Value>,
}

impl GetDefault2200ResponseEdgesExtraInner {
    pub fn new() -> GetDefault2200ResponseEdgesExtraInner {
        GetDefault2200ResponseEdgesExtraInner {
            edge_id: None,
            extra: None,
        }
    }
}

