/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetGeoJsonSnapping200ResponseFeaturesInnerProperties : Feature properties
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGeoJsonSnapping200ResponseFeaturesInnerProperties {
    /// \"Name of the street the closest accessible point is situated on. Only for `resolve_locations=true` and only if name is available.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Distance between the `source/destination` Location and the used point on the routing graph in meters.
    #[serde(rename = "snapped_distance", skip_serializing_if = "Option::is_none")]
    pub snapped_distance: Option<f64>,
    /// Index of the requested location
    #[serde(rename = "source_id", skip_serializing_if = "Option::is_none")]
    pub source_id: Option<i32>,
}

impl GetGeoJsonSnapping200ResponseFeaturesInnerProperties {
    /// Feature properties
    pub fn new() -> GetGeoJsonSnapping200ResponseFeaturesInnerProperties {
        GetGeoJsonSnapping200ResponseFeaturesInnerProperties {
            name: None,
            snapped_distance: None,
            source_id: None,
        }
    }
}

