/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefault3200ResponseRoutesInnerExtrasValue : An object representing one of the extra info items requested
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault3200ResponseRoutesInnerExtrasValue {
    /// A list of values representing a section of the route. The individual values are:  Value 1: Indice of the staring point of the geometry for this section, Value 2: Indice of the end point of the geoemetry for this sections, Value 3: [Value](https://GIScience.github.io/openrouteservice/api-reference/endpoints/directions/extra-info/) assigned to this section.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<Vec<i64>>>,
    /// List representing the summary of the extra info items.
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Vec<models::GetDefault3200ResponseRoutesInnerExtrasValueSummaryInner>>,
}

impl GetDefault3200ResponseRoutesInnerExtrasValue {
    /// An object representing one of the extra info items requested
    pub fn new() -> GetDefault3200ResponseRoutesInnerExtrasValue {
        GetDefault3200ResponseRoutesInnerExtrasValue {
            values: None,
            summary: None,
        }
    }
}

