/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGpxRoute200ResponseMetadataBounds {
    #[serde(rename = "minLon", skip_serializing_if = "Option::is_none")]
    pub min_lon: Option<f64>,
    #[serde(rename = "maxLon", skip_serializing_if = "Option::is_none")]
    pub max_lon: Option<f64>,
    #[serde(rename = "minLat", skip_serializing_if = "Option::is_none")]
    pub min_lat: Option<f64>,
    #[serde(rename = "maxLat", skip_serializing_if = "Option::is_none")]
    pub max_lat: Option<f64>,
    #[serde(rename = "asArray", skip_serializing_if = "Option::is_none")]
    pub as_array: Option<Vec<f64>>,
}

impl GetGpxRoute200ResponseMetadataBounds {
    pub fn new() -> GetGpxRoute200ResponseMetadataBounds {
        GetGpxRoute200ResponseMetadataBounds {
            min_lon: None,
            max_lon: None,
            min_lat: None,
            max_lat: None,
            as_array: None,
        }
    }
}

