/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefault3200ResponseRoutesInnerSegmentsInner : List containing the segments and its correspoding steps which make up the route.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault3200ResponseRoutesInnerSegmentsInner {
    /// Contains the distance of the segment in specified units.
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
    /// Contains the duration of the segment in seconds.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    /// List containing the specific steps the segment consists of.
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<models::GetDefault3200ResponseRoutesInnerSegmentsInnerStepsInner>>,
    /// Contains the deviation compared to a straight line that would have the factor `1`. Double the Distance would be a `2`.
    #[serde(rename = "detourfactor", skip_serializing_if = "Option::is_none")]
    pub detourfactor: Option<f64>,
    /// Contains the proportion of the route in percent.
    #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
    pub percentage: Option<f64>,
    /// Contains the average speed of this segment in km/h.
    #[serde(rename = "avgspeed", skip_serializing_if = "Option::is_none")]
    pub avgspeed: Option<f64>,
    ///  Contains ascent of this segment in metres.
    #[serde(rename = "ascent", skip_serializing_if = "Option::is_none")]
    pub ascent: Option<f64>,
    /// Contains descent of this segment in metres.
    #[serde(rename = "descent", skip_serializing_if = "Option::is_none")]
    pub descent: Option<f64>,
}

impl GetDefault3200ResponseRoutesInnerSegmentsInner {
    /// List containing the segments and its correspoding steps which make up the route.
    pub fn new() -> GetDefault3200ResponseRoutesInnerSegmentsInner {
        GetDefault3200ResponseRoutesInnerSegmentsInner {
            distance: None,
            duration: None,
            steps: None,
            detourfactor: None,
            percentage: None,
            avgspeed: None,
            ascent: None,
            descent: None,
        }
    }
}

