/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefault3200ResponseRoutesInnerSummary : Contains total sums of duration, route distance and actual distance of the route.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault3200ResponseRoutesInnerSummary {
    /// Total route distance in specified units.
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
    /// Total duration in seconds.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    /// Total ascent in meters.
    #[serde(rename = "ascent", skip_serializing_if = "Option::is_none")]
    pub ascent: Option<f64>,
    /// Total descent in meters.
    #[serde(rename = "descent", skip_serializing_if = "Option::is_none")]
    pub descent: Option<f64>,
    #[serde(rename = "transfers", skip_serializing_if = "Option::is_none")]
    pub transfers: Option<i32>,
    #[serde(rename = "fare", skip_serializing_if = "Option::is_none")]
    pub fare: Option<i32>,
}

impl GetDefault3200ResponseRoutesInnerSummary {
    /// Contains total sums of duration, route distance and actual distance of the route.
    pub fn new() -> GetDefault3200ResponseRoutesInnerSummary {
        GetDefault3200ResponseRoutesInnerSummary {
            distance: None,
            duration: None,
            ascent: None,
            descent: None,
            transfers: None,
            fare: None,
        }
    }
}

