/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefaultIsochrones200ResponseFeaturesInner {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<models::RouteOptionsAvoidPolygons>,
}

impl GetDefaultIsochrones200ResponseFeaturesInner {
    pub fn new() -> GetDefaultIsochrones200ResponseFeaturesInner {
        GetDefaultIsochrones200ResponseFeaturesInner {
            r#type: None,
            geometry: None,
        }
    }
}

