/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGpxRoute200ResponseMetadata {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<serde_json::Value>,
    #[serde(rename = "copyright", skip_serializing_if = "Option::is_none")]
    pub copyright: Option<serde_json::Value>,
    #[serde(rename = "timeGenerated", skip_serializing_if = "Option::is_none")]
    pub time_generated: Option<String>,
    #[serde(rename = "bounds", skip_serializing_if = "Option::is_none")]
    pub bounds: Option<Box<models::GetGpxRoute200ResponseMetadataBounds>>,
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<serde_json::Value>,
}

impl GetGpxRoute200ResponseMetadata {
    pub fn new() -> GetGpxRoute200ResponseMetadata {
        GetGpxRoute200ResponseMetadata {
            name: None,
            description: None,
            author: None,
            copyright: None,
            time_generated: None,
            bounds: None,
            extensions: None,
        }
    }
}

