/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGpxRoute200Response {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::GetGpxRoute200ResponseMetadata>>,
    #[serde(rename = "routes", skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<serde_json::Value>>,
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<serde_json::Value>,
    #[serde(rename = "gpxRouteElements", skip_serializing_if = "Option::is_none")]
    pub gpx_route_elements: Option<Vec<serde_json::Value>>,
}

impl GetGpxRoute200Response {
    pub fn new() -> GetGpxRoute200Response {
        GetGpxRoute200Response {
            metadata: None,
            routes: None,
            extensions: None,
            gpx_route_elements: None,
        }
    }
}

