/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefaultRequest : Snapping service endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefaultRequest {
    /// The locations to be snapped as array of `longitude/latitude` pairs.
    #[serde(rename = "locations")]
    pub locations: Vec<Vec<f64>>,
    /// Arbitrary identification string of the request reflected in the meta information.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Maximum radius in meters around given coordinates to search for graph edges.
    #[serde(rename = "radius")]
    pub radius: f64,
}

impl GetDefaultRequest {
    /// Snapping service endpoint.
    pub fn new(locations: Vec<Vec<f64>>, radius: f64) -> GetDefaultRequest {
        GetDefaultRequest {
            locations,
            id: None,
            radius,
        }
    }
}

