/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefault3200ResponseRoutesInnerSegmentsInnerStepsInnerManeuver : Maneuver object of the step
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault3200ResponseRoutesInnerSegmentsInnerStepsInnerManeuver {
    /// The coordinate of the point where a maneuver takes place.
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<f64>>,
    /// The azimuth angle (in degrees) of the direction right before the maneuver.
    #[serde(rename = "bearing_before", skip_serializing_if = "Option::is_none")]
    pub bearing_before: Option<i32>,
    /// The azimuth angle (in degrees) of the direction right after the maneuver.
    #[serde(rename = "bearing_after", skip_serializing_if = "Option::is_none")]
    pub bearing_after: Option<i32>,
}

impl GetDefault3200ResponseRoutesInnerSegmentsInnerStepsInnerManeuver {
    /// Maneuver object of the step
    pub fn new() -> GetDefault3200ResponseRoutesInnerSegmentsInnerStepsInnerManeuver {
        GetDefault3200ResponseRoutesInnerSegmentsInnerStepsInnerManeuver {
            location: None,
            bearing_before: None,
            bearing_after: None,
        }
    }
}

