/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefault3200ResponseRoutesInnerExtrasValueSummaryInner : List representing the summary of the extra info items.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault3200ResponseRoutesInnerExtrasValueSummaryInner {
    /// [Value](https://giscience.github.io/openrouteservice/api-reference/endpoints/directions/extra-info/) of a info category.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
    /// Cumulative distance of this value.
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
    /// Category percentage of the entire route.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
}

impl GetDefault3200ResponseRoutesInnerExtrasValueSummaryInner {
    /// List representing the summary of the extra info items.
    pub fn new() -> GetDefault3200ResponseRoutesInnerExtrasValueSummaryInner {
        GetDefault3200ResponseRoutesInnerExtrasValueSummaryInner {
            value: None,
            distance: None,
            amount: None,
        }
    }
}

