/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDefault1200ResponseDestinationsInner : The individual destinations of the matrix calculations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDefault1200ResponseDestinationsInner {
    /// {longitude},{latitude} coordinates of the closest accessible point on the routing graph
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<f64>>,
    /// Name of the street the closest accessible point is situated on. Only for `resolve_locations=true` and only if name is available.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Distance between the `source/destination` Location and the used point on the routing graph in meters.
    #[serde(rename = "snapped_distance", skip_serializing_if = "Option::is_none")]
    pub snapped_distance: Option<f64>,
}

impl GetDefault1200ResponseDestinationsInner {
    /// The individual destinations of the matrix calculations.
    pub fn new() -> GetDefault1200ResponseDestinationsInner {
        GetDefault1200ResponseDestinationsInner {
            location: None,
            name: None,
            snapped_distance: None,
        }
    }
}

