/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GraphExportService : The request payload
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GraphExportService {
    /// The bounding box to use for the request as an array of `longitude/latitude` pairs
    #[serde(rename = "bbox")]
    pub bbox: Vec<Vec<f64>>,
    /// Arbitrary identification string of the request reflected in the meta information.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Whether to return the exact geometry of the graph or a simplified (beeline) representation.
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<bool>,
}

impl GraphExportService {
    /// The request payload
    pub fn new(bbox: Vec<Vec<f64>>) -> GraphExportService {
        GraphExportService {
            bbox,
            id: None,
            geometry: None,
        }
    }
}

