/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IsochronesRequest : The JSON body request sent to the isochrones service which defines options and parameters regarding the isochrones to generate.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IsochronesRequest {
    /// Arbitrary identification string of the request reflected in the meta information.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The locations to use for the route as an array of `longitude/latitude` pairs in WGS 84 (EPSG:4326)
    #[serde(rename = "locations")]
    pub locations: Vec<Vec<f64>>,
    /// `start` treats the location(s) as starting point, `destination` as goal.
    #[serde(rename = "location_type", skip_serializing_if = "Option::is_none")]
    pub location_type: Option<LocationType>,
    /// Maximum range value of the analysis in **seconds** for time and **metres** for distance.Alternatively a comma separated list of specific range values. Ranges will be the same for all locations.
    #[serde(rename = "range")]
    pub range: Vec<f64>,
    /// Specifies the isochrones reachability type.
    #[serde(rename = "range_type", skip_serializing_if = "Option::is_none")]
    pub range_type: Option<RangeType>,
    /// Specifies the distance units only if `range_type` is set to distance. Default: m. 
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<Units>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::RouteOptions>>,
    /// Specifies the area unit. Default: m. 
    #[serde(rename = "area_units", skip_serializing_if = "Option::is_none")]
    pub area_units: Option<AreaUnits>,
    /// Specifies whether to return intersecting polygons. 
    #[serde(rename = "intersections", skip_serializing_if = "Option::is_none")]
    pub intersections: Option<bool>,
    /// List of isochrones attributes - `area` - area of the isochrone polygon - `reachfactor` - reachability score between 0 and 1 This factor is calculated as the ratio between the area of a circle with a radius based on the average speed and the area of the isochrone polygon. - `total_pop` - total population within the polygon The data used for this is the [Global Human Settlement Layer (GHSL)](https://ghsl.jrc.ec.europa.eu/ghs_pop2023.php) from the European Commission. Note that while the dataset was published in 2023, the most recent data contained is from 2020. This is used by the openrouteservice at a resolution of 100m. 
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<Attributes>>,
    /// Interval of isochrones or equidistants. This is only used if a single range value is given. Value in **seconds** for time and **meters** for distance.
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<f64>,
    /// Applies a level of generalisation to the isochrone polygons generated as a `smoothing_factor` between `0` and `100.0`. Generalisation is produced by determining a maximum length of a connecting line between two points found on the outside of a containing polygon. If the distance is larger than a threshold value, the line between the two points is removed and a smaller connecting line between other points is used. Note that the minimum length of this connecting line is ~1333m, and so when the `smoothing_factor` results in a distance smaller than this, the minimum value is used. The threshold value is determined as `(maximum_radius_of_isochrone / 100) * smoothing_factor`. Therefore, a value closer to 100 will result in a more generalised shape. The polygon generation algorithm is based on Duckham and al. (2008) `\"Efficient generation of simple polygons for characterizing the shape of a set of points in the plane.\"`
    #[serde(rename = "smoothing", skip_serializing_if = "Option::is_none")]
    pub smoothing: Option<f64>,
}

impl IsochronesRequest {
    /// The JSON body request sent to the isochrones service which defines options and parameters regarding the isochrones to generate.
    pub fn new(locations: Vec<Vec<f64>>, range: Vec<f64>) -> IsochronesRequest {
        IsochronesRequest {
            id: None,
            locations,
            location_type: None,
            range,
            range_type: None,
            units: None,
            options: None,
            area_units: None,
            intersections: None,
            attributes: None,
            interval: None,
            smoothing: None,
        }
    }
}
/// `start` treats the location(s) as starting point, `destination` as goal.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LocationType {
    #[serde(rename = "start")]
    Start,
    #[serde(rename = "destination")]
    Destination,
}

impl Default for LocationType {
    fn default() -> LocationType {
        Self::Start
    }
}
/// Specifies the isochrones reachability type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RangeType {
    #[serde(rename = "time")]
    Time,
    #[serde(rename = "distance")]
    Distance,
}

impl Default for RangeType {
    fn default() -> RangeType {
        Self::Time
    }
}
/// Specifies the distance units only if `range_type` is set to distance. Default: m. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Units {
    #[serde(rename = "m")]
    M,
    #[serde(rename = "km")]
    Km,
    #[serde(rename = "mi")]
    Mi,
}

impl Default for Units {
    fn default() -> Units {
        Self::M
    }
}
/// Specifies the area unit. Default: m. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AreaUnits {
    #[serde(rename = "m")]
    M,
    #[serde(rename = "km")]
    Km,
    #[serde(rename = "mi")]
    Mi,
}

impl Default for AreaUnits {
    fn default() -> AreaUnits {
        Self::M
    }
}
/// List of isochrones attributes - `area` - area of the isochrone polygon - `reachfactor` - reachability score between 0 and 1 This factor is calculated as the ratio between the area of a circle with a radius based on the average speed and the area of the isochrone polygon. - `total_pop` - total population within the polygon The data used for this is the [Global Human Settlement Layer (GHSL)](https://ghsl.jrc.ec.europa.eu/ghs_pop2023.php) from the European Commission. Note that while the dataset was published in 2023, the most recent data contained is from 2020. This is used by the openrouteservice at a resolution of 100m. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Attributes {
    #[serde(rename = "area")]
    Area,
    #[serde(rename = "reachfactor")]
    Reachfactor,
    #[serde(rename = "total_pop")]
    TotalPop,
}

impl Default for Attributes {
    fn default() -> Attributes {
        Self::Area
    }
}

