/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsonStep : Step of a route segment
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonStep {
    /// The distance for the step in metres.
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
    /// The duration for the step in seconds.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    /// The [instruction](https://giscience.github.io/openrouteservice/api-reference/endpoints/directions/instruction-types) action for symbolisation purposes.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    /// The routing instruction text for the step.
    #[serde(rename = "instruction", skip_serializing_if = "Option::is_none")]
    pub instruction: Option<String>,
    /// The name of the next street.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Only for roundabouts. Contains the number of the exit to take.
    #[serde(rename = "exit_number", skip_serializing_if = "Option::is_none")]
    pub exit_number: Option<i32>,
    /// Contains the bearing of the entrance and all passed exits in a roundabout.
    #[serde(rename = "exit_bearings", skip_serializing_if = "Option::is_none")]
    pub exit_bearings: Option<Vec<i32>>,
    /// List containing the indices of the steps start- and endpoint corresponding to the *geometry*.
    #[serde(rename = "way_points", skip_serializing_if = "Option::is_none")]
    pub way_points: Option<Vec<i32>>,
    #[serde(rename = "maneuver", skip_serializing_if = "Option::is_none")]
    pub maneuver: Option<Box<models::GetDefault3200ResponseRoutesInnerSegmentsInnerStepsInnerManeuver>>,
}

impl JsonStep {
    /// Step of a route segment
    pub fn new() -> JsonStep {
        JsonStep {
            distance: None,
            duration: None,
            r#type: None,
            instruction: None,
            name: None,
            exit_number: None,
            exit_bearings: None,
            way_points: None,
            maneuver: None,
        }
    }
}

