/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsonLeg : Leg of a route
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonLeg {
    /// The type of the leg, possible values are currently 'walk' and 'pt'.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The departure location of the leg.
    #[serde(rename = "departure_location", skip_serializing_if = "Option::is_none")]
    pub departure_location: Option<String>,
    /// The headsign of the public transport vehicle of the leg.
    #[serde(rename = "trip_headsign", skip_serializing_if = "Option::is_none")]
    pub trip_headsign: Option<String>,
    /// The public transport route name of the leg.
    #[serde(rename = "route_long_name", skip_serializing_if = "Option::is_none")]
    pub route_long_name: Option<String>,
    /// The public transport route name (short version) of the leg.
    #[serde(rename = "route_short_name", skip_serializing_if = "Option::is_none")]
    pub route_short_name: Option<String>,
    /// The route description of the leg (if provided in the GTFS data set).
    #[serde(rename = "route_desc", skip_serializing_if = "Option::is_none")]
    pub route_desc: Option<String>,
    /// The route type of the leg (if provided in the GTFS data set).
    #[serde(rename = "route_type", skip_serializing_if = "Option::is_none")]
    pub route_type: Option<i32>,
    /// The distance for the leg in metres.
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
    /// The duration for the leg in seconds.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    /// Departure date and time
    #[serde(rename = "departure", skip_serializing_if = "Option::is_none")]
    pub departure: Option<String>,
    /// Arrival date and time
    #[serde(rename = "arrival", skip_serializing_if = "Option::is_none")]
    pub arrival: Option<String>,
    /// The feed ID this public transport leg based its information from.
    #[serde(rename = "feed_id", skip_serializing_if = "Option::is_none")]
    pub feed_id: Option<String>,
    /// The trip ID of this public transport leg.
    #[serde(rename = "trip_id", skip_serializing_if = "Option::is_none")]
    pub trip_id: Option<String>,
    /// The route ID of this public transport leg.
    #[serde(rename = "route_id", skip_serializing_if = "Option::is_none")]
    pub route_id: Option<String>,
    /// Whether the legs continues in the same vehicle as the previous one.
    #[serde(rename = "is_in_same_vehicle_as_previous", skip_serializing_if = "Option::is_none")]
    pub is_in_same_vehicle_as_previous: Option<bool>,
    /// The geometry of the leg. This is an encoded polyline.
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<String>,
    /// List containing the specific steps the segment consists of.
    #[serde(rename = "instructions", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<Vec<models::GetDefault3200ResponseRoutesInnerSegmentsInnerStepsInner>>,
    /// List containing the stops the along the leg.
    #[serde(rename = "stops", skip_serializing_if = "Option::is_none")]
    pub stops: Option<Vec<models::GetDefault3200ResponseRoutesInnerLegsInnerStopsInner>>,
}

impl JsonLeg {
    /// Leg of a route
    pub fn new() -> JsonLeg {
        JsonLeg {
            r#type: None,
            departure_location: None,
            trip_headsign: None,
            route_long_name: None,
            route_short_name: None,
            route_desc: None,
            route_type: None,
            distance: None,
            duration: None,
            departure: None,
            arrival: None,
            feed_id: None,
            trip_id: None,
            route_id: None,
            is_in_same_vehicle_as_previous: None,
            geometry: None,
            instructions: None,
            stops: None,
        }
    }
}

