/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonEdge {
    /// Id of the start point of the edge
    #[serde(rename = "fromId", skip_serializing_if = "Option::is_none")]
    pub from_id: Option<i32>,
    /// Id of the end point of the edge
    #[serde(rename = "toId", skip_serializing_if = "Option::is_none")]
    pub to_id: Option<i32>,
    /// Weight of the corresponding edge in the given bounding box
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
}

impl JsonEdge {
    pub fn new() -> JsonEdge {
        JsonEdge {
            from_id: None,
            to_id: None,
            weight: None,
        }
    }
}

