/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsonptStop : Stop of a public transport leg
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonptStop {
    /// The ID of the stop.
    #[serde(rename = "stop_id", skip_serializing_if = "Option::is_none")]
    pub stop_id: Option<String>,
    /// The name of the stop.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The location of the stop.
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<f64>>,
    /// Arrival time of the stop.
    #[serde(rename = "arrival_time", skip_serializing_if = "Option::is_none")]
    pub arrival_time: Option<String>,
    /// Planned arrival time of the stop.
    #[serde(rename = "planned_arrival_time", skip_serializing_if = "Option::is_none")]
    pub planned_arrival_time: Option<String>,
    /// Predicted arrival time of the stop.
    #[serde(rename = "predicted_arrival_time", skip_serializing_if = "Option::is_none")]
    pub predicted_arrival_time: Option<String>,
    /// Whether arrival at the stop was cancelled.
    #[serde(rename = "arrival_cancelled", skip_serializing_if = "Option::is_none")]
    pub arrival_cancelled: Option<bool>,
    /// Departure time of the stop.
    #[serde(rename = "departure_time", skip_serializing_if = "Option::is_none")]
    pub departure_time: Option<String>,
    /// Planned departure time of the stop.
    #[serde(rename = "planned_departure_time", skip_serializing_if = "Option::is_none")]
    pub planned_departure_time: Option<String>,
    /// Predicted departure time of the stop.
    #[serde(rename = "predicted_departure_time", skip_serializing_if = "Option::is_none")]
    pub predicted_departure_time: Option<String>,
    /// Whether departure at the stop was cancelled.
    #[serde(rename = "departure_cancelled", skip_serializing_if = "Option::is_none")]
    pub departure_cancelled: Option<bool>,
}

impl JsonptStop {
    /// Stop of a public transport leg
    pub fn new() -> JsonptStop {
        JsonptStop {
            stop_id: None,
            name: None,
            location: None,
            arrival_time: None,
            planned_arrival_time: None,
            predicted_arrival_time: None,
            arrival_cancelled: None,
            departure_time: None,
            planned_departure_time: None,
            predicted_departure_time: None,
            departure_cancelled: None,
        }
    }
}

