/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MatchingRequest : The request payload
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchingRequest {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<models::PostMatchingRequestFeatures>,
    /// Arbitrary identification string of the request reflected in the meta information.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl MatchingRequest {
    /// The request payload
    pub fn new() -> MatchingRequest {
        MatchingRequest {
            key: None,
            features: None,
            id: None,
        }
    }
}

