/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MatrixRequest : The JSON body request sent to the matrix service which defines options and parameters regarding the matrix to generate.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatrixRequest {
    /// List of comma separated lists of `longitude,latitude` coordinates in WGS 84 (EPSG:4326)
    #[serde(rename = "locations")]
    pub locations: Vec<Vec<f64>>,
    /// Arbitrary identification string of the request reflected in the meta information.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of indices that refers to the list of locations (starting with `0`). `{index_1},{index_2}[,{index_N} ...]` or `all` (default). example `[0,3]` for the first and fourth locations 
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<String>>,
    /// A list of indices that refers to the list of locations (starting with `0`). `{index_1},{index_2}[,{index_N} ...]` or `all` (default). `[0,3]` for the first and fourth locations 
    #[serde(rename = "destinations", skip_serializing_if = "Option::is_none")]
    pub destinations: Option<Vec<String>>,
    /// Specifies a list of returned metrics. \"* `distance` - Returns distance matrix for specified points in defined `units`. * `duration` - Returns duration matrix for specified points in **seconds**. 
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<Metrics>>,
    /// Specifies whether given locations are resolved or not. If the parameter value set to `true`, every element in `destinations` and `sources` will contain a `name` element that identifies the name of the closest street. Default is `false`. 
    #[serde(rename = "resolve_locations", skip_serializing_if = "Option::is_none")]
    pub resolve_locations: Option<bool>,
    /// Specifies the distance unit. Default: m.
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<Units>,
}

impl MatrixRequest {
    /// The JSON body request sent to the matrix service which defines options and parameters regarding the matrix to generate.
    pub fn new(locations: Vec<Vec<f64>>) -> MatrixRequest {
        MatrixRequest {
            locations,
            id: None,
            sources: None,
            destinations: None,
            metrics: None,
            resolve_locations: None,
            units: None,
        }
    }
}
/// Specifies a list of returned metrics. \"* `distance` - Returns distance matrix for specified points in defined `units`. * `duration` - Returns duration matrix for specified points in **seconds**. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Metrics {
    #[serde(rename = "distance")]
    Distance,
    #[serde(rename = "duration")]
    Duration,
}

impl Default for Metrics {
    fn default() -> Metrics {
        Self::Distance
    }
}
/// Specifies the distance unit. Default: m.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Units {
    #[serde(rename = "m")]
    M,
    #[serde(rename = "km")]
    Km,
    #[serde(rename = "mi")]
    Mi,
}

impl Default for Units {
    fn default() -> Units {
        Self::M
    }
}

