/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MatrixResponse : The Matrix Response contains one matrix for each specified `metrics` value.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatrixResponse {
    /// The durations of the matrix calculations.
    #[serde(rename = "durations", skip_serializing_if = "Option::is_none")]
    pub durations: Option<Vec<Vec<f64>>>,
    /// The distances of the matrix calculations.
    #[serde(rename = "distances", skip_serializing_if = "Option::is_none")]
    pub distances: Option<Vec<Vec<f64>>>,
    /// The individual destinations of the matrix calculations.
    #[serde(rename = "destinations", skip_serializing_if = "Option::is_none")]
    pub destinations: Option<Vec<models::GetDefault1200ResponseDestinationsInner>>,
    /// The individual sources of the matrix calculations.
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<models::GetDefault1200ResponseSourcesInner>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::GetDefault1200ResponseMetadata>>,
}

impl MatrixResponse {
    /// The Matrix Response contains one matrix for each specified `metrics` value.
    pub fn new() -> MatrixResponse {
        MatrixResponse {
            durations: None,
            distances: None,
            destinations: None,
            sources: None,
            metadata: None,
        }
    }
}

