/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Objects {
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<Box<models::GetTopoJsonExport200ResponseObjectsNetwork>>,
}

impl Objects {
    pub fn new() -> Objects {
        Objects {
            network: None,
        }
    }
}

