/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProfileParameters : Specifies additional routing parameters. For all profiles except `driving-car`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileParameters {
    #[serde(rename = "weightings", skip_serializing_if = "Option::is_none")]
    pub weightings: Option<Box<models::ProfileWeightings>>,
    #[serde(rename = "restrictions", skip_serializing_if = "Option::is_none")]
    pub restrictions: Option<Box<models::ProfileParametersRestrictions>>,
    /// Specifies whether to enforce that only ways with known information on surface quality be taken into account - default false
    #[serde(rename = "surface_quality_known", skip_serializing_if = "Option::is_none")]
    pub surface_quality_known: Option<bool>,
    /// Specifies if ways that might not be suitable (e.g. unknown pedestrian usage) should be included in finding routes - default false
    #[serde(rename = "allow_unsuitable", skip_serializing_if = "Option::is_none")]
    pub allow_unsuitable: Option<bool>,
}

impl ProfileParameters {
    /// Specifies additional routing parameters. For all profiles except `driving-car`.
    pub fn new() -> ProfileParameters {
        ProfileParameters {
            weightings: None,
            restrictions: None,
            surface_quality_known: None,
            allow_unsuitable: None,
        }
    }
}

