/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProfileWeightings : Describe additional weightings to be applied to edges on the routing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileWeightings {
    /// Specifies the fitness level for `cycling-*` profiles.   level: 0 = Novice, 1 = Moderate, 2 = Amateur, 3 = Pro. The prefered gradient increases with level.
    #[serde(rename = "steepness_difficulty", skip_serializing_if = "Option::is_none")]
    pub steepness_difficulty: Option<i32>,
    /// Specifies the Green factor for `foot-*` profiles.  factor: Multiplication factor range from 0 to 1. 0 is the green routing base factor without multiplying it by the manual factor and is already different from normal routing. 1 will prefer ways through green areas over a shorter route.
    #[serde(rename = "green", skip_serializing_if = "Option::is_none")]
    pub green: Option<f32>,
    /// Specifies the Quiet factor for foot-* profiles.  factor: Multiplication factor range from 0 to 1. 0 is the quiet routing base factor without multiplying it by the manual factor and is already different from normal routing. 1 will prefer quiet ways over a shorter route.
    #[serde(rename = "quiet", skip_serializing_if = "Option::is_none")]
    pub quiet: Option<f32>,
    /// Specifies the shadow factor for `foot-*` profiles.  factor: Multiplication factor range from 0 to 1. 0 is the shadow routing base factor without multiplying it by the manual factor and is already different from normal routing. 1 will prefer ways through shadow areas over a shorter route.
    #[serde(rename = "shadow", skip_serializing_if = "Option::is_none")]
    pub shadow: Option<f32>,
}

impl ProfileWeightings {
    /// Describe additional weightings to be applied to edges on the routing.
    pub fn new() -> ProfileWeightings {
        ProfileWeightings {
            steepness_difficulty: None,
            green: None,
            quiet: None,
            shadow: None,
        }
    }
}

