/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Properties {
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    #[serde(rename = "node_from", skip_serializing_if = "Option::is_none")]
    pub node_from: Option<i64>,
    #[serde(rename = "node_to", skip_serializing_if = "Option::is_none")]
    pub node_to: Option<i64>,
    #[serde(rename = "osm_id", skip_serializing_if = "Option::is_none")]
    pub osm_id: Option<i64>,
    #[serde(rename = "both_directions", skip_serializing_if = "Option::is_none")]
    pub both_directions: Option<bool>,
    #[serde(rename = "speed", skip_serializing_if = "Option::is_none")]
    pub speed: Option<f64>,
    #[serde(rename = "speed_reverse", skip_serializing_if = "Option::is_none")]
    pub speed_reverse: Option<f64>,
    #[serde(rename = "ors_ids", skip_serializing_if = "Option::is_none")]
    pub ors_ids: Option<Vec<i32>>,
    #[serde(rename = "ors_nodes", skip_serializing_if = "Option::is_none")]
    pub ors_nodes: Option<Vec<i32>>,
    #[serde(rename = "distances", skip_serializing_if = "Option::is_none")]
    pub distances: Option<Vec<f64>>,
}

impl Properties {
    pub fn new() -> Properties {
        Properties {
            weight: None,
            node_from: None,
            node_to: None,
            osm_id: None,
            both_directions: None,
            speed: None,
            speed_reverse: None,
            ors_ids: None,
            ors_nodes: None,
            distances: None,
        }
    }
}

