/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoundTripRouteOptions : Specifies the parameters for generating round trip routes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoundTripRouteOptions {
    /// The target length of the route in `m` (note that this is a preferred value, but results may be different).
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<f32>,
    /// The number of points to use on the route. Larger values create more circular routes.
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<i32>,
    /// A seed to use for adding randomisation to the overall direction of the generated route
    #[serde(rename = "seed", skip_serializing_if = "Option::is_none")]
    pub seed: Option<i64>,
}

impl RoundTripRouteOptions {
    /// Specifies the parameters for generating round trip routes.
    pub fn new() -> RoundTripRouteOptions {
        RoundTripRouteOptions {
            length: None,
            points: None,
            seed: None,
        }
    }
}

