/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RouteRequestCustomModelGeoJsonFeature : Map of areas that can be referenced in speed and priority rules
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteRequestCustomModelGeoJsonFeature {
    /// GeoJSON type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "geometry", skip_serializing_if = "Option::is_none")]
    pub geometry: Option<Box<models::DirectionsServiceCustomModelAreasValueGeometry>>,
}

impl RouteRequestCustomModelGeoJsonFeature {
    /// Map of areas that can be referenced in speed and priority rules
    pub fn new() -> RouteRequestCustomModelGeoJsonFeature {
        RouteRequestCustomModelGeoJsonFeature {
            r#type: None,
            geometry: None,
        }
    }
}

