/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RouteOptions : Advanced options for routing
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteOptions {
    /// List of features to avoid. 
    #[serde(rename = "avoid_features", skip_serializing_if = "Option::is_none")]
    pub avoid_features: Option<Vec<AvoidFeatures>>,
    /// Specify which type of border crossing to avoid
    #[serde(rename = "avoid_borders", skip_serializing_if = "Option::is_none")]
    pub avoid_borders: Option<AvoidBorders>,
    /// List of countries to exclude from matrix with `driving-*` profiles. Can be used together with `'avoid_borders': 'controlled'`. `[ 11, 193 ]` would exclude Austria and Switzerland. List of countries and application examples can be found [here](https://giscience.github.io/openrouteservice/technical-details/country-list). Also, ISO standard country codes cna be used in place of the numerical ids, for example, DE or DEU for Germany. 
    #[serde(rename = "avoid_countries", skip_serializing_if = "Option::is_none")]
    pub avoid_countries: Option<Vec<String>>,
    /// Definition of the vehicle type.
    #[serde(rename = "vehicle_type", skip_serializing_if = "Option::is_none")]
    pub vehicle_type: Option<VehicleType>,
    #[serde(rename = "profile_params", skip_serializing_if = "Option::is_none")]
    pub profile_params: Option<Box<models::ProfileParameters>>,
    #[serde(rename = "avoid_polygons", skip_serializing_if = "Option::is_none")]
    pub avoid_polygons: Option<models::RouteOptionsAvoidPolygons>,
    #[serde(rename = "round_trip", skip_serializing_if = "Option::is_none")]
    pub round_trip: Option<Box<models::RoundTripRouteOptions>>,
}

impl RouteOptions {
    /// Advanced options for routing
    pub fn new() -> RouteOptions {
        RouteOptions {
            avoid_features: None,
            avoid_borders: None,
            avoid_countries: None,
            vehicle_type: None,
            profile_params: None,
            avoid_polygons: None,
            round_trip: None,
        }
    }
}
/// List of features to avoid. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AvoidFeatures {
    #[serde(rename = "highways")]
    Highways,
    #[serde(rename = "tollways")]
    Tollways,
    #[serde(rename = "ferries")]
    Ferries,
    #[serde(rename = "fords")]
    Fords,
    #[serde(rename = "steps")]
    Steps,
}

impl Default for AvoidFeatures {
    fn default() -> AvoidFeatures {
        Self::Highways
    }
}
/// Specify which type of border crossing to avoid
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AvoidBorders {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "controlled")]
    Controlled,
    #[serde(rename = "none")]
    None,
}

impl Default for AvoidBorders {
    fn default() -> AvoidBorders {
        Self::All
    }
}
/// Definition of the vehicle type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VehicleType {
    #[serde(rename = "hgv")]
    Hgv,
    #[serde(rename = "bus")]
    Bus,
    #[serde(rename = "agricultural")]
    Agricultural,
    #[serde(rename = "delivery")]
    Delivery,
    #[serde(rename = "forestry")]
    Forestry,
    #[serde(rename = "goods")]
    Goods,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for VehicleType {
    fn default() -> VehicleType {
        Self::Hgv
    }
}

