/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RouteResponseInfo : Information about the request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteResponseInfo {
    /// ID of the request (as passed in by the query)
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Copyright and attribution information
    #[serde(rename = "attribution", skip_serializing_if = "Option::is_none")]
    pub attribution: Option<String>,
    /// The service that was requested
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
    /// Time that the request was made (UNIX Epoch time)
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::DirectionsService>>,
    #[serde(rename = "engine", skip_serializing_if = "Option::is_none")]
    pub engine: Option<Box<models::GetDefault200ResponseMetadataEngine>>,
    /// System message
    #[serde(rename = "system_message", skip_serializing_if = "Option::is_none")]
    pub system_message: Option<String>,
}

impl RouteResponseInfo {
    /// Information about the request
    pub fn new() -> RouteResponseInfo {
        RouteResponseInfo {
            id: None,
            attribution: None,
            service: None,
            timestamp: None,
            query: None,
            engine: None,
            system_message: None,
        }
    }
}

