/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RouteRequestCustomModel : Specifies custom model for weighting.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteRequestCustomModel {
    /// Parameter determining the influence of the distance between two points on the edge weight
    #[serde(rename = "distance_influence", skip_serializing_if = "Option::is_none")]
    pub distance_influence: Option<f64>,
    /// Array of objects describing rules to be applied to the speed of edges
    #[serde(rename = "speed", skip_serializing_if = "Option::is_none")]
    pub speed: Option<Vec<models::DirectionsServiceCustomModelSpeedInner>>,
    /// Array of objects describing rules to be applied to the priority of edges
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Vec<models::DirectionsServiceCustomModelSpeedInner>>,
    /// Map of areas that can be referenced in speed and priority rules
    #[serde(rename = "areas", skip_serializing_if = "Option::is_none")]
    pub areas: Option<std::collections::HashMap<String, models::DirectionsServiceCustomModelAreasValue>>,
}

impl RouteRequestCustomModel {
    /// Specifies custom model for weighting.
    pub fn new() -> RouteRequestCustomModel {
        RouteRequestCustomModel {
            distance_influence: None,
            speed: None,
            priority: None,
            areas: None,
        }
    }
}

