/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RouteOptionsAvoidPolygons : Comprises areas to be avoided for the route. Formatted in GeoJSON as either a Polygon or Multipolygon object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteOptionsAvoidPolygons {
    #[serde(rename = "empty", skip_serializing_if = "Option::is_none")]
    pub empty: Option<bool>,
}

impl RouteOptionsAvoidPolygons {
    /// Comprises areas to be avoided for the route. Formatted in GeoJSON as either a Polygon or Multipolygon object.
    pub fn new() -> RouteOptionsAvoidPolygons {
        RouteOptionsAvoidPolygons {
            empty: None,
        }
    }
}

