/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SnappingResponse : The Snapping Response contains the snapped coordinates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnappingResponse {
    /// The snapped locations as coordinates and snapping distance.
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<models::GetDefault200ResponseLocationsInner>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::GetDefault200ResponseMetadata>>,
}

impl SnappingResponse {
    /// The Snapping Response contains the snapped coordinates.
    pub fn new() -> SnappingResponse {
        SnappingResponse {
            locations: None,
            metadata: None,
        }
    }
}

