/*
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 9.5.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * The version of the OpenAPI document: v2
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopoJsonExportResponse {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "objects", skip_serializing_if = "Option::is_none")]
    pub objects: Option<Box<models::GetTopoJsonExport200ResponseObjects>>,
    #[serde(rename = "arcs", skip_serializing_if = "Option::is_none")]
    pub arcs: Option<Vec<Vec<Vec<f64>>>>,
    #[serde(rename = "bbox", skip_serializing_if = "Option::is_none")]
    pub bbox: Option<Vec<f64>>,
}

impl TopoJsonExportResponse {
    pub fn new() -> TopoJsonExportResponse {
        TopoJsonExportResponse {
            r#type: None,
            objects: None,
            arcs: None,
            bbox: None,
        }
    }
}

